export interface Question {
  question: string;
  options: [string, string, string];
  correct: number;
}

export const QUESTIONS: Question[] = [
  { question: 'Mars has ___ moons', options: ['2', '5', '4'], correct: 0 },
  { question: 'first man in space', options: ['Y. Gagarin', 'N. Armstrong', 'B. Yeltsin'], correct: 0 },
  { question: 'first man to step on the moon', options: ['N. Armstrong', 'M. Jackson', 'E. Aldrin'], correct: 0 },
  { question: 'first shuttle to land on the moon', options: ['Apollo 11', 'Apollo 13', 'Apollo 15'], correct: 0 },
  { question: 'not in our solar system', options: ['Centauri', 'Sun', 'Pluto'], correct: 0 },
  { question: 'closest to the earth', options: ['Venus', 'Mars', 'Saturn'], correct: 0 },
  { question: 'a space telescope', options: ['Hubble', 'Sagan', 'Keck'], correct: 0 },
  { question: 'larger than the others', options: ['Sun', 'Earth', 'Moon'], correct: 0 },
  { question: 'farther away from the sun', options: ['Uranus', 'Jupiter', 'Saturn'], correct: 0 },
  { question: 'the earth orbits the sun once in ___ days', options: ['365', '30', '180'], correct: 0 },
  { question: 'the summer solstice occurs in ___', options: ['June', 'May', 'July'], correct: 0 },
  { question: 'the winter solstice occurs in ___', options: ['December', 'November', 'January'], correct: 0 },
  { question: 'the moon orbits the earth once in ___ days', options: ['28', '21', '7'], correct: 0 },
  { question: 'smaller than the others', options: ['Moon', 'Mars', 'Earth'], correct: 0 },
  { question: 'largest planet in our solar system', options: ['Jupiter', 'Saturn', 'Uranus'], correct: 0 },
  { question: 'the name of our galaxy', options: ['Milky Way', 'Solaris', 'Centauri'], correct: 0 },
  { question: 'closest galaxy to ours', options: ['Andromeda', 'Alpha Centauri', 'Sagan C'], correct: 0 },
  { question: 'an earth science', options: ['geology', 'mathematics', 'physics'], correct: 0 },
  { question: 'the study of soil', options: ['pedology', 'zoology', 'jumangy'], correct: 0 },
  { question: 'water', options: ['H2O', 'CH4', 'CH3O'], correct: 0 },
  { question: 'Cr stands for', options: ['chromium', 'charmendium', 'chloride'], correct: 0 },
  { question: 'Mg stands for', options: ['magnesium', 'manganese', 'madagascar'], correct: 0 },
  { question: 'Fe stands for', options: ['iron', 'silver', 'gold'], correct: 0 },
  { question: 'K stands for', options: ['potassium', 'carbon', 'kraken'], correct: 0 },
  { question: 'Os stands for', options: ['osmium', 'oxygen', 'osmosis'], correct: 0 },
  { question: 'N stands for', options: ['nitrogen', 'neon', 'narnium'], correct: 0 },
  { question: 'U stands for', options: ['uranium', 'uxium', 'ukrainium'], correct: 0 },
  { question: 'Au stands for', options: ['gold', 'aluminum', 'rock'], correct: 0 },
  { question: 'Br stands for', options: ['bromine', 'bromium', 'brosupium'], correct: 0 },
  { question: 'Ag stands for', options: ['silver', 'bronze', 'gold'], correct: 0 },
  { question: 'water boils at ___ degrees Celcius', options: ['100', '0', '212'], correct: 0 },
  { question: 'water freezes at ___ degrees Kelvin', options: ['273', '0', '-100'], correct: 0 },
  { question: 'subatomic particle', options: ['proton', 'hydrogen', 'molecule'], correct: 0 },
  { question: 'negatively charged', options: ['electron', 'neutron', 'proton'], correct: 0 },
  { question: 'positively charged', options: ['proton', 'neutron', 'electron'], correct: 0 },
  { question: 'Einstein\'s theory of ___', options: ['relativity', 'gravity', 'theories'], correct: 0 },
  { question: 'created the vaccine for rabies', options: ['L. Pasteur', 'C. Darwin', 'E. Jenner'], correct: 0 },
  { question: 'director of the Manhattan Project', options: ['J. R. Oppenheimer', 'A. Einstein', 'Dr. Manhattan'], correct: 0 },
  { question: '100 kilograms equal ___ pounds', options: ['220', '160', '40'], correct: 0 },
  { question: '440 pounds equal ___ kilograms', options: ['200', '100', '110'], correct: 0 },
  { question: '1 second equals ___ miliseconds', options: ['1000', '100', '60'], correct: 0 },
  { question: '25 hours equal ___ minutes', options: ['1500', '2500', '1250'], correct: 0 },
  { question: '96 hours equal ___ days', options: ['4', '12', '16'], correct: 0 },
  { question: '3 meters equal ___ feet', options: ['10', '6', '12'], correct: 0 },
  { question: '1 metric ton equals ___ kilograms', options: ['1000', '220', '2000'], correct: 0 },
  { question: '2 liters equal ___ milliliters', options: ['2000', '1200', '240'], correct: 0 },
  { question: 'the industrial revolution began in', options: ['UK', 'Russia', 'France'], correct: 0 },
  { question: 'Darwin\'s theory of ___', options: ['evolution', 'gravity', 'revolution'], correct: 0 },
  { question: 'inventor of the Tesla coil', options: ['N. Tesla', 'A. Coil', 'T. Edison'], correct: 0 },
  { question: 'fell on Newton\'s head', options: ['apple', 'moon', 'monkey'], correct: 0 },
  { question: 'force equals mass times ___', options: ['acceleration', 'speed', 'volume'], correct: 0 },
  { question: 'there is no Nobel prize in ___', options: ['mathematics', 'literature', 'physics'], correct: 0 },
  { question: 'won the Nobel prize twice', options: ['M. Curie', 'G. Foreman', 'A. Einstein'], correct: 0 },
  { question: 'discovered the X-ray', options: ['R.D. Roentgen', 'C. Xavier', 'M. Jackson'], correct: 0 },
  { question: 'invented the telephone', options: ['A. Graham Bell', 'T. Edison', 'T. Duwde'], correct: 0 },
  { question: 'he wrote "On the Origin of Species"', options: ['C. Darwin', 'R. Dawkins', 'R. Downey Jr.'], correct: 0 },
  { question: '1 gram of fat has ___ calories', options: ['9', '6', '3'], correct: 0 },
  { question: '1 gram of protein has ___ calories', options: ['4', '7', '9001'], correct: 0 },
  { question: 'invented the dynamite', options: ['A. Nobel', 'C. Orrekt', 'M. Curie'], correct: 0 },
  { question: 'inventors of the airplane', options: ['Wright Brothers', 'Roeng Sisters', 'Jackson Family'], correct: 0 },
  { question: 'inventor of the revolver', options: ['S. Colt', 'F. Cent', 'A. K. Foresven'], correct: 0 },
  { question: 'inventor of the diesel engine', options: ['R. Diesel', 'S. Benzene', 'H. Ford'], correct: 0 },
  { question: 'smaller than the others', options: ['destroyer', 'battleship', 'aircraft Carrier'], correct: 0 },
  { question: 'the study of encryption', options: ['cryptography', 'calligraphy', 'calisthenics'], correct: 0 },
  { question: 'liquid at room temperature', options: ['mercury', 'uranium', 'lead'], correct: 0 },
  { question: 'chemical explosive', options: ['TNT', 'ABD', 'C3PO'], correct: 0 },
  { question: 'density is mass over', options: ['volume', 'length', 'hardness'], correct: 0 },
  { question: 'pioneer of aviation in helicopters', options: ['I. Sikorsky', 'R. U. Boeing', 'H. L. Kopter'], correct: 0 },
  { question: 'the human body\'s largest organ', options: ['skin', 'brain', 'heart'], correct: 0 },
  { question: 'herbivores eat', options: ['plants', 'bacon', 'planets'], correct: 0 },
  { question: 'dinosaurs became extinct ___ years ago', options: ['65 million', '145 million', '325 million'], correct: 0 },
  { question: 'not a kingdom in biology', options: ['mammalia', 'fungi', 'animalia'], correct: 0 },
  { question: 'a nucleid acid', options: ['DNA', 'cytoplasm', 'nucleus'], correct: 0 },
  { question: 'the functional basic unit of life', options: ['cell', 'gene', 'DNA'], correct: 0 },
  { question: 'change in velocity over time', options: ['acceleration', 'speed', 'direction'], correct: 0 },
  { question: 'ISU = International System of ___', options: ['Units', 'Unions', 'Unicorns'], correct: 0 },
  { question: 'not a constellation', options: ['Leon', 'Chamaeleon', 'Aries'], correct: 0 },
  { question: 'the male hormone', options: ['testosterone', 'estrogen', 'insulin'], correct: 0 },
  { question: 'the female hormone', options: ['estrogen', 'testosterone', 'insulin'], correct: 0 },
  { question: 'tegulates blood sugar', options: ['insulin', 'estrogen', 'testosterone'], correct: 0 },
  { question: 'concentrates bile', options: ['gall bladder', 'stomach', 'pancreas'], correct: 0 },
  { question: 'ammonia', options: ['NH3', 'H2SO4', 'CH3O'], correct: 0 },
  { question: 'not a basic human taste', options: ['sugarness', 'saltiness', 'bitterness'], correct: 0 },
  { question: 'a basic human taste', options: ['sweetness', 'hotness', 'sugarness'], correct: 0 },
  { question: 'the periodic table has ___ elements', options: ['118', '84', '156'], correct: 0 },
  { question: 'contains the ozone layer', options: ['stratosphere', 'lithosphere', 'pseudosphere'], correct: 0 },
  { question: 'ozone', options: ['O3', 'O2', 'CH2O'], correct: 0 },
  { question: 'stored energy', options: ['potential', 'kinetic', 'nucleic'], correct: 0 },
  { question: 'joule is a unit of', options: ['energy', 'acceleration', 'magnetism'], correct: 0 },
  { question: 'specific ___ capacity', options: ['heat', 'dilution', 'magnet'], correct: 0 },
  { question: 'a barometer measures', options: ['pressure', 'temperature', 'elevation'], correct: 0 },
  { question: 'Mr. Avogadro has a ___ named after him', options: ['constant', 'cookbook', 'country'], correct: 0 },
  { question: 'creator of the periodic table', options: ['D. Mendelev', 'I. Newton', 'N. Tesla'], correct: 0 },
  { question: 'X-rays were discovered in', options: ['1895', '1922', '1938'], correct: 0 },
  { question: 'has less gravity', options: ['Moon', 'Earth', 'Mars'], correct: 0 },
  { question: 'atomic number is the number of ___', options: ['protons', 'neutrons', 'electrons'], correct: 0 },
  { question: 'the nucleus does not contain ___', options: ['electrons', 'neutrons', 'protons'], correct: 0 },
  { question: 'won the Nobel prize in economics', options: ['J. Nash', 'A. Einstein', 'T. Count'], correct: 0 },
  { question: 'famous for his cat', options: ['E. Schrodinger', 'A. Einstein', 'J. Nash'], correct: 0 },
  { question: 'H stands for', options: ['hydrogen', 'helium', 'hassium'], correct: 0 },
  { question: 'most common gas in the atmosphere', options: ['nitrogen', 'oxygen', 'nexgen'], correct: 0 },
  { question: 'a snowflake has', options: ['6 sides', '12 sides', '9 sides'], correct: 0 },
  { question: 'speed of sound', options: ['340 m/s', '1337 m/s', '440 m/s'], correct: 0 },
  { question: 'faster than the others', options: ['light', 'sound', 'cheetah'], correct: 0 },
  { question: 'smaller than the others', options: ['proton', 'molecule', 'baby elephant'], correct: 0 },
  { question: 'deoxyribonucleic acid', options: ['DNA', 'DBO', 'DOA'], correct: 0 },
  { question: 'ribonucleic acid', options: ['RNA', 'DNA', 'RNB'], correct: 0 },
  { question: 'rapid ___ movement sleep', options: ['eye', 'feet', 'tooth'], correct: 0 },
  { question: 'Kelvin is a unit of', options: ['temperature', 'distance', 'mass'], correct: 0 },
  { question: 'second is a unit of', options: ['time', 'space', 'olympics'], correct: 0 },
  { question: 'ascorbic acid', options: ['vitamin C', 'vitamin D', 'vitamin S'], correct: 0 },
  { question: 'not a part of the paleolithic diet', options: ['donuts', 'meat', 'fruits'], correct: 0 },
  { question: 'CERN is located in ___', options: ['Geneva', 'Brussels', 'Texas'], correct: 0 },
  { question: 'soluble in water', options: ['table salt', 'olive oil', 'metal spoon'], correct: 0 },
  { question: 'not a type of fish', options: ['silverback', 'bass', 'jack'], correct: 0 },
  { question: 'a type of fish', options: ['barracuda', 'seabear', 'big blue blind'], correct: 0 },
  { question: 'the atomic number of gold is ___', options: ['79', '24', '92'], correct: 0 },
  { question: 'the atomic number of hydrogen is ___', options: ['1', '4', '12'], correct: 0 },
  { question: 'the atomic number of silver is ___', options: ['47', '79', '33'], correct: 0 },
  { question: 'larger than the others', options: ['Jupiter', 'Uranus', 'Venus'], correct: 0 },
  { question: 'the answer is "the answer"', options: ['the answer', 'what', 'false'], correct: 0 },
  { question: 'you mother\'s mother\'s daughter', options: ['your aunt', 'your brother', 'your grandma'], correct: 0 },
  { question: 'the first word in this sentence', options: ['the', 'second', 'sentence'], correct: 0 },
  { question: 'overtake the third and you are __', options: ['third', 'second', 'first'], correct: 0 },
  { question: 'a triplet boy has at least ___ siblings', options: ['two', 'three', 'four'], correct: 0 },
  { question: '24th letter in the english alphabet', options: ['x', 'z', 'p'], correct: 0 },
  { question: '13th letter in the english alphabet', options: ['m', 'j', 'p'], correct: 0 },
  { question: '6th letter in the english alphabet', options: ['f', 'g', 'h'], correct: 0 },
  { question: 'most native speakers', options: ['Mandarin', 'English', 'Spanish'], correct: 0 },
  { question: 'pick "this"', options: ['this', 'that', 'those'], correct: 0 },
  { question: 'you are reading ___', options: ['the answer', 'a book', 'the newspaper'], correct: 0 },
  { question: 'your uncle\'s father\'s son', options: ['your father', 'your mother', 'your son'], correct: 0 },
  { question: 'the name of this game', options: ['Super Smart', 'Epic Smarts', 'Smarty Smarts'], correct: 0 },
  { question: 'you are playing ___', options: ['Super Smart', 'Epic Smarts', 'Smartrr'], correct: 0 },
  { question: 'yellow mixed with red', options: ['orange', 'violet', 'blue'], correct: 0 },
  { question: 'red mixed with blue', options: ['violet', 'orange', 'green'], correct: 0 },
  { question: 'blue mixed with yellow', options: ['green', 'violet', 'turquoise'], correct: 0 },
  { question: 'not a primary color', options: ['green', 'yellow', 'red'], correct: 0 },
  { question: 'a primary color', options: ['red', 'green', 'violet'], correct: 0 },
  { question: 'a fruit', options: ['tomato', 'celery', 'spinach'], correct: 0 },
  { question: 'type of underwear', options: ['boxers', 'kittens', 'puppies'], correct: 0 },
  { question: 'has opposable thumbs', options: ['gorilla', 'whale', 'dog'], correct: 0 },
  { question: 'rock beats ___', options: ['scissors', 'paper', 'stone'], correct: 0 },
  { question: 'paper beats ___', options: ['rock', 'scissors', 'pencil'], correct: 0 },
  { question: '2012 olympics took place in ___', options: ['London', 'Istanbul', 'Paris'], correct: 0 },
  { question: '2008 olympics took place in ___', options: ['Beijing', 'Munich', 'London'], correct: 0 },
  { question: 'not an olympic sport', options: ['squash', 'fencing', 'taekwondo'], correct: 0 },
  { question: 'an olympic sport', options: ['triathlon', 'sumo', 'chess'], correct: 0 },
  { question: 'a spider has ___ legs', options: ['8', '6', '9'], correct: 0 },
  { question: 'the day before tomorrow', options: ['today', 'yesterday', 'tomorrow'], correct: 0 },
  { question: 'the day after yesterday', options: ['today', 'yesterday', 'tomorrow'], correct: 0 },
  { question: 'two days before wednesday', options: ['monday', 'thursday', 'saturday'], correct: 0 },
  { question: 'three days after last tuesday', options: ['friday', 'thursday', 'sunday'], correct: 0 },
  { question: 'the day before next wednesday', options: ['tuesday', 'last friday', 'thursday'], correct: 0 },
  { question: 'the number of weeks in three years', options: ['156', '144', '112'], correct: 0 },
  { question: 'three letters before i', options: ['f', 'g', 'k'], correct: 0 },
  { question: 'between the letters m and o', options: ['n', 'k', 'p'], correct: 0 },
  { question: 'the letter before u', options: ['t', 'v', 'x'], correct: 0 },
  { question: 'opposite of "opposite"', options: ['same', 'different', 'neutral'], correct: 0 },
  { question: 'antonym of synonym', options: ['antonym', 'synonym', 'acronym'], correct: 0 },
  { question: 'pick the odd one', options: ['3', '2', '4'], correct: 0 },
  { question: 'above the heart', options: ['brain', 'stomach', 'intestine'], correct: 0 },
  { question: '100% discount makes it ___', options: ['free', 'double the price', 'half the price'], correct: 0 },
  { question: 'two million two hundred thirty two', options: ['2000232', '2003232', '2002032'], correct: 0 },
  { question: 'one million four thousand four', options: ['1004004', '1040044', '1000444'], correct: 0 },
  { question: 'five hundred thousand fifty five', options: ['500055', '500555', '550055'], correct: 0 },
  { question: 'four hundred thousand sixty six', options: ['400066', '406606', '400660'], correct: 0 },
  { question: 'nine thousand four hundred six', options: ['9406', '9046', '9466'], correct: 0 },
  { question: 'five million four hundred fifty two', options: ['5000452', '5004052', '5044052'], correct: 0 },
  { question: 'six thousand six hundred seventy', options: ['6670', '66707', '6607'], correct: 0 },
  { question: 'fits in your pocket', options: ['a pen', 'a human', 'an elephant'], correct: 0 },
  { question: 'pick "true" or "false"', options: ['true', 'can\'t', 'what'], correct: 0 },
  { question: 'a spider wears ___ shoes', options: ['0', '6', '12'], correct: 0 },
  { question: 'a word in this sentence', options: ['word', 'letters', 'where'], correct: 0 },
  { question: 'the second word in this sentence', options: ['second', 'word', 'sentence'], correct: 0 },
  { question: 'the four letter word in the middle', options: ['word', 'middle', 'the'], correct: 0 },
  { question: 'fourth letter of "fourth"', options: ['r', 'f', 't'], correct: 0 },
  { question: 'comes after the word "after"', options: ['the', 'word', 'after'], correct: 0 },
  { question: 'second letter of "this"', options: ['h', 't', 's'], correct: 0 },
  { question: 'third letter of "what"', options: ['a', 'h', 'w'], correct: 0 },
  { question: 'fourth letter of "smart"', options: ['r', 't', 's'], correct: 0 },
  { question: 'sixth letter of "hippopotamus"', options: ['p', 'o', 't'], correct: 0 },
  { question: 'the word before "after"', options: ['before', 'after', 'why'], correct: 0 },
  { question: 'the word after "after"', options: ['after', 'word', 'what'], correct: 0 },
  { question: 'the letter after p', options: ['q', 'r', 'o'], correct: 0 },
  { question: 'the answer is "your clue"', options: ['your clue', 'wrong', 'the answer'], correct: 0 },
  { question: 'second letter after b', options: ['d', 'e', 'f'], correct: 0 },
  { question: '"it is" spelled backwards', options: ['si ti', 'it si', 'ti is'], correct: 0 },
  { question: '"loot" spelled backwards', options: ['tool', 'loto', 'lol'], correct: 0 },
  { question: '"letters" spelled backwards', options: ['srettel', 'slettel', 'sreltel'], correct: 0 },
  { question: '"refer" spelled backwards', options: ['refer', 'rerfef', 'ferrer'], correct: 0 },
  { question: '"rhythm" spelled backwards', options: ['mhtyhr', 'mhythr', 'mthyhr'], correct: 0 },
  { question: '"murder" spelled backwards', options: ['redrum', 'redmur', 'murmur'], correct: 0 },
  { question: '"live" spelled backwards', options: ['evil', 'alive', 'vile'], correct: 0 },
  { question: '"something" spelled backwards', options: ['gnihtemos', 'gnithomes', 'gnihmetos'], correct: 0 },
  { question: 'a letter in "a letter"', options: ['t', 'p', 'q'], correct: 0 },
  { question: 'the last letter of this sentence', options: ['e', 'n', 's'], correct: 0 },
  { question: 'a year in the third century', options: ['298', '311', '23'], correct: 0 },
  { question: 'second day of last year was in ___', options: ['January', 'December', 'June'], correct: 0 },
  { question: 'second month after June', options: ['August', 'May', 'October'], correct: 0 },
  { question: 'a year in the fifth century', options: ['444', '555', '666'], correct: 0 },
  { question: 'the answer is "incorrect"', options: ['incorrect', '2+2=5', 'false'], correct: 0 },
  { question: '80 minutes past 11:00', options: ['12:20', '11:60', '12:40'], correct: 0 },
  { question: '75 minutes past 10:00', options: ['11:15', '10:10', '11:45'], correct: 0 },
  { question: '44 minutes past 11:00', options: ['11:44', '10:16', '11:40'], correct: 0 },
  { question: '80 minutes past 2:59', options: ['4:19', '4:39', '4:49'], correct: 0 },
  { question: 'even this number is even', options: ['4', '3', '5'], correct: 0 },
  { question: '"11" and "22" are not the answer', options: ['99', '11', '22'], correct: 0 },
  { question: 'odd numbers are not the answer', options: ['12', '21', '33'], correct: 0 },
  { question: 'you are ___ at this game', options: ['awesome', 'wrong answer', 'wrong answer'], correct: 0 },
  { question: 'the answer is "what"', options: ['what', 'why', 'how'], correct: 0 },
  { question: 'fifth letter of "tricky question"', options: ['k', 'i', 'q'], correct: 0 },
  { question: 'overtake the second and you are ___', options: ['second', 'third', 'first'], correct: 0 },
  { question: 'second letter of "letter"', options: ['e', 'l', 't'], correct: 0 },
  { question: 'rhymes with "rhyme"', options: ['crime', 'drama', 'eminem'], correct: 0 },
  { question: 'a minute before midnight', options: ['23:59', '12:59', '11:11'], correct: 0 },
  { question: 'two years after last year', options: ['next year', 'this year', '2112'], correct: 0 },
  { question: 'two days after yesterday', options: ['tomorrow', 'today', 'yesterday'], correct: 0 },
  { question: 'one day before tomorrow', options: ['today', 'yesterday', 'whataday'], correct: 0 },
  { question: 'tenth month of the year', options: ['October', 'September', 'November'], correct: 0 },
  { question: 'third month after may', options: ['August', 'June', 'October'], correct: 0 },
  { question: 'you are ___ smart', options: ['super', 'don\'t pick this', 'don\'t pick this'], correct: 0 },
  { question: 'smaller than two million', options: ['855352', '9218112', '3441123'], correct: 0 },
  { question: 'the day after today', options: ['tomorrow', 'yesterday', 'today'], correct: 0 },
  { question: 'that apple phone people brag about', options: ['iphone', 'myphone', 'al caphone'], correct: 0 },
  { question: 'this question has ___', options: ['3 choices', '8 words', '99 problems'], correct: 0 },
  { question: 'the number of colors in the rainbow', options: ['7', '8', '9'], correct: 0 },
  { question: 'the 28 day month', options: ['February', 'January', 'June'], correct: 0 },
  { question: 'pure gold is ___', options: ['24 karats', '14 karats', '28 karats'], correct: 0 },
  { question: 'a chessboard has ___', options: ['64 squares', '72 squares', '44 squares'], correct: 0 },
  { question: 'a basketball team has ___', options: ['5 players', '8 players', '3 players'], correct: 0 },
  { question: 'we are in the ___ century', options: ['21st', '20th', '19th'], correct: 0 },
  { question: 'the number of words in this sentence', options: ['7', '8', '5'], correct: 0 },
  { question: 'your father\'s mother\'s son', options: ['your father', 'your mother', 'your son'], correct: 0 },
  { question: 'the answer starts with "c"', options: ['correct', 'think hard', 'try again'], correct: 0 },
  { question: 'this question has ___', options: ['three words', 'eight choices', 'fifty letters'], correct: 0 },
  { question: 'complete all the achievements!', options: ['sure thing!', 'don\'t pick this', 'don\'t pick this'], correct: 0 },
  { question: 'your avatar looks like a brain!', options: ['it does!', 'don\'t pick this', 'don\'t pick this'], correct: 0 },
  { question: 'the person playing this game is', options: ['me', 'my pet', 'michael jackson'], correct: 0 },
  { question: 'find "the secret"', options: ['the secret', 'where', 'i give up'], correct: 0 },
  { question: 'the correct answer is "false"', options: ['false', 'correct', 'next'], correct: 0 },
  { question: 'the last letter of "the alphabet"', options: ['t', 'a', 'u'], correct: 0 },
  { question: 'the last letter of "something else"', options: ['e', 's', 'h'], correct: 0 },
  { question: 'born on may 16th, your sign is ___', options: ['Taurus', 'Aries', 'Gemini'], correct: 0 },
  { question: 'all but 4 of your 10 eggs break', options: ['4 eggs left', '6 eggs left', '14 eggs left'], correct: 0 },
  { question: 'a type of shellfish', options: ['mussel', 'muscle', 'muzzle'], correct: 0 },
  { question: 'born on January 15th, your sign is ___', options: ['Capricorn', 'Leo', 'Unicorn'], correct: 0 },
  { question: 'born on october 21st, your sign is ___', options: ['Libra', 'Gemini', 'Taurus'], correct: 0 },
  { question: 'born on june 4th, your sign is ___', options: ['Gemini', 'Leo', 'Snape'], correct: 0 },
  { question: 'born on July 24th, your sign is ___', options: ['Leo', 'Libra', 'Pisces'], correct: 0 },
  { question: 'born in April, your sign could be ___', options: ['Taurus', 'Gemini', 'Capricorn'], correct: 0 },
  { question: 'a type of women\'s shoes', options: ['pumps', 'kats', 'tires'], correct: 0 },
  { question: 'not a type of women\'s shoes', options: ['sharpies', 'flats', 'stillettos'], correct: 0 },
  { question: 'there is a ___ missing in this sentence', options: ['word', 'hard', 'fragile'], correct: 0 },
  { question: 'can\'t wear these on your feet', options: ['scandals', 'shoes', 'socks'], correct: 0 },
  { question: 'up is down when down is ___', options: ['up', 'down', 'a rabbit'], correct: 0 },
  { question: 'not a zodiac sign', options: ['Tauri', 'Virgo', 'Sagittarius'], correct: 0 },
  { question: 'not a zodiac sign', options: ['Scorpion', 'Gemini', 'Pisces'], correct: 0 },
  { question: 'a zodiac sign', options: ['Leo', 'Leon', 'Mufasa'], correct: 0 },
  { question: 'the missing ___ in this sentence', options: ['word', 'going to', 'ridiculous'], correct: 0 },
  { question: 'pick the blank answer', options: ['', 'not blank', 'occupied'], correct: 0 },
  { question: 'the answer has two letters', options: ['no', 'yes', 'maybe'], correct: 0 },
  { question: 'the answer is "hidden"', options: ['hidden', 'right here', 'found it'], correct: 0 },
  { question: 'this sentence has no ___', options: ['punctuation', 'letters', 'words'], correct: 0 },
  { question: 'a game mode in Super Smart', options: ['arcade', 'blitz', 'time limit'], correct: 0 },
  { question: 'an Apple product', options: ['iPod', 'MacBro', 'iShall'], correct: 0 },
  { question: 'this word is used twice in this sentence', options: ['this', 'in', 'word'], correct: 0 },
  { question: '43 minutes past 13:43', options: ['2:26 PM', '14:46', '15:16'], correct: 0 },
  { question: 'pick the correct ___ to score', options: ['answer', 'elephant', 'flower'], correct: 0 },
  { question: 'a long time ago', options: ['1257 AD', '10144 AD', '5723 AD'], correct: 0 },
  { question: 'the answer times the answer is 1', options: ['1', '4', '9'], correct: 0 },
  { question: 'the first letter of the sixth word', options: ['s', 'w', 't'], correct: 0 },
  { question: 'the second letter in this sentence', options: ['h', 's', 'e'], correct: 0 },
  { question: 'they call this a full stop in the UK', options: ['.', '?', '-'], correct: 0 },
  { question: 'the answer is not "funny" or "ironic"', options: ['yes', 'ironic', 'funny'], correct: 0 },
  { question: 'A=B and B=C, so the answer is "D"', options: ['D', 'B', 'banana'], correct: 0 },
  { question: 'spell "backwards" forwards', options: ['backwards', 'sdrawkcab', 'sdrawrof'], correct: 0 },
  { question: 'heavier than you', options: ['775 kg', '775 g', '775 mg'], correct: 0 },
  { question: '"what" is a ___ letter word', options: ['four', 'three', 'one'], correct: 0 },
  { question: 'the second letter of the second word', options: ['e', 's', 'o'], correct: 0 },
  { question: 'the answer is "straight forward"', options: ['straight forward', 'stick', 'banana'], correct: 0 },
  { question: 'single people are ___', options: ['single', 'double', 'triple'], correct: 0 },
  { question: 'you use this in a handshake', options: ['hand', 'thermometer', 'giraffe'], correct: 0 },
  { question: 'resistance against the machines is ___', options: ['futile', 'don\'t pick this', 'don\'t pick this'], correct: 0 },
  { question: 'not one of your relatives', options: ['your shoe', 'your father', 'your grandmother'], correct: 0 },
  { question: 'shouldn\'t wear these on your feet', options: ['hats', 'socks', 'shoes'], correct: 0 },
  { question: 'artificial sweetner', options: ['sucralose', 'fructose', 'dextrose'], correct: 0 },
  { question: 'a standard 52-card deck has ___ cards', options: ['52', '44', '145'], correct: 0 },
  { question: 'not a card game', options: ['polo', 'solitaire', 'bridge'], correct: 0 },
  { question: 'probability of an impossible event', options: ['0/1', '1/2', '1/1'], correct: 0 },
  { question: '0.5 can also be expressed as ___', options: ['1/2', '2/1', '1.2'], correct: 0 },
  { question: 'can\'t find this letter in this sentence', options: ['m', 'l', 'd'], correct: 0 },
  { question: 'spell "forwards" backwards', options: ['sdrawrof', 'swardrof', 'sdrowarf'], correct: 0 },
  { question: 'a half-court shot is worth 3 points in ___', options: ['basketball', 'football', 'hockey'], correct: 0 },
  { question: 'no penalty shots in ___', options: ['basketball', 'soccer', 'hockey'], correct: 0 },
  { question: 'no yellow cards in ___', options: ['baseball', 'soccer', 'volleyball'], correct: 0 },
  { question: 'Union of European Football Associations', options: ['UEFA', 'FIFA', 'NFL'], correct: 0 },
  { question: 'illegal on most commercial flights', options: ['smoking', 'moonwalking', 'yawning'], correct: 0 },
  { question: 'don\'t pick "your nose"', options: ['seriously', 'your nose', 'your nose'], correct: 0 },
  { question: 'pick "your nose"', options: ['your nose', 'don\'t do it', 'so impolite'], correct: 0 },
  { question: 'pick the largest even number', options: ['37752', '88649', '22286'], correct: 0 },
  { question: 'pick the smallest odd number', options: ['913', '912', '904'], correct: 0 },
  { question: '3 seconds is ___ minutes', options: ['0.05', '0.20', '0.5'], correct: 0 },
  { question: '252 seconds is ___ minutes', options: ['4.2', '3.8', '4.42'], correct: 0 },
  { question: 'your father\'s mother\'s granddaughter', options: ['your sister', 'your mother', 'your daughter'], correct: 0 },
  { question: 'the number of letters in this sentence', options: ['32', '81', '16'], correct: 0 },
  { question: 'born in April, your sign can\'t be ___', options: ['Virgo', 'Aries', 'Taurus'], correct: 0 },
  { question: 'this month is 31 days long', options: ['October', 'February', 'March'], correct: 0 },
  { question: 'an Italian dish with rice', options: ['risotto', 'salame', 'ciabatta'], correct: 0 },
  { question: 'an Italian dish with pasta', options: ['ravioli', 'risotto', 'gelato'], correct: 0 },
  { question: 'an Japanese dish with rice', options: ['onigiri', 'sashimi', 'tempura'], correct: 0 },
  { question: 'Japanese art of paper folding', options: ['origami', 'organism', 'originy'], correct: 0 },
  { question: 'traditional Japanese puppet theater', options: ['banruki', 'kabuki', 'satsuma'], correct: 0 },
  { question: 'traditional Japanese theater', options: ['kabuki', 'miko', 'kansai'], correct: 0 },
  { question: '10 plus the number of ears on three dogs', options: ['16', '4', '24'], correct: 0 },
  { question: '4 minus the number of states in the USA', options: ['-46', '-54', '-55'], correct: 0 },
  { question: '33 plus the the number choices available', options: ['36', '30', '35'], correct: 0 },
  { question: 'number of letter "e"s in this sentence', options: ['7', '6', '11'], correct: 0 },
  { question: 'pick 1, 2, 6, or 4', options: ['6', '5', '8'], correct: 0 },
  { question: 'you can read the correct answer out loud', options: ['yes', '', ''], correct: 0 },
  { question: 'German automobile manufacturer', options: ['Smart', 'Buick', 'Pontiac'], correct: 0 },
  { question: 'an odd number times two', options: ['6', '4', '16'], correct: 0 },
  { question: 'an even number times two', options: ['16', '22', '39'], correct: 0 },
  { question: 'has more gravity than the others', options: ['earth', 'ear', 'elephant'], correct: 0 },
  { question: 'fifth month of the year', options: ['May', 'April', 'March'], correct: 0 },
  { question: 'a young goat is called a ___', options: ['kid', 'goatee', 'meat'], correct: 0 },
  { question: 'can\'t spell "slaughter" without ___', options: ['laughter', 'dime', 'moon'], correct: 0 },
  { question: 'the answer has letters', options: ['false', '80075', ';__;'], correct: 0 },
  { question: 'this sentence doesn\'t have the letter ___', options: ['m', 'n', 'v'], correct: 0 },
  { question: 'a computer programming language', options: ['python', 'snake', 'MnM++'], correct: 0 },
  { question: 'you start with ___ in Arcade mode', options: ['60 seconds', '45 seconds', '90 seconds'], correct: 0 },
  { question: 'you start with ___ in Classic mode', options: ['0 points', '80 seconds', '6 choices'], correct: 0 },
  { question: 'you have ___ seconds left', options: ['less than 100', 'more than 300', '442'], correct: 0 },
  { question: '612 seconds is ___ minutes', options: ['10.2', '11.8', '10.12'], correct: 0 },
  { question: '99 minutes is ___ seconds', options: ['5940', '6000', '5994'], correct: 0 },
  { question: '1156.3 minutes is ___ minutes', options: ['1156.3', '19.27', '69372'], correct: 0 },
  { question: 'this is usually round', options: ['a bowling ball', 'a box', 'a shark'], correct: 0 },
  { question: 'the classical smiley face', options: [':)', ';>', '+<:B'], correct: 0 },
  { question: 'your dog\'s biological child could be ___', options: ['your puppy', 'your cat', 'your mother'], correct: 0 },
  { question: 'the answer has no letters', options: ['321895419', '21341L2B3', '4144A4B88'], correct: 0 },
  { question: 'you can have no memory of ___', options: ['tomorrow', 'two weeks ago', 'yesterday'], correct: 0 },
  { question: 'this question has ___ when completed', options: ['seven words', 'twenty five letters', 'sixteen syllables'], correct: 0 },
  { question: 'this question doesn\'t have the letter ___', options: ['c', 'i', 'v'], correct: 0 },
  { question: 'a person who plays the drums', options: ['drummer', 'guitarist', 'loser'], correct: 0 },
  { question: 'you have found the secret question', options: ['correct', 'don\'t pick this', 'don\'t pick this'], correct: 0 },
  { question: 'this month is 30 days long', options: ['June', 'July', 'August'], correct: 0 },
  { question: 'this question has a ___', options: ['correct answer', 'number in it', 'capital letter'], correct: 0 },
  { question: '777 weeks is ___ days', options: ['5439', '111', '11'], correct: 0 },
  { question: 'the first letter of the first word', options: ['t', 'f', 'l'], correct: 0 },
  { question: 'the Indian Ocean is ___', options: ['wet', 'in Indiana', 'a lake'], correct: 0 },
  { question: 'Speaking two languages', options: ['bilingual', 'bicentennial', 'biennial'], correct: 0 },
  { question: 'Make a word using  "l, o, c, o"', options: ['cool', 'lock', 'loot'], correct: 0 },
  { question: 'Make a word using  "t, a, l, e, s"', options: ['steal', 'later', 'steel'], correct: 0 },
  { question: 'Make a word using  "l, i, v, e"', options: ['evil', 'life', 'vein'], correct: 0 },
  { question: 'Make a word using  "s, t, e, e, r"', options: ['reset', 'setter', 'stream'], correct: 0 },
  { question: 'Make a word using  "t, e, r, r, a, i, n"', options: ['trainer', 'narrate', 'retained'], correct: 0 },
  { question: 'Make a word using   "e, l, m, o"', options: ['mole', 'loom', 'mall'], correct: 0 },
  { question: 'Make a word using  "g, a, r, d, e, n"', options: ['danger', 'gender', 'ranger'], correct: 0 },
  { question: 'Make a word using  "c, a, t, e, r, e, d"', options: ['reacted', 'creator', 'crated'], correct: 0 },
  { question: 'make a word using  "r, e, d, a, c, t"', options: ['carted', 'catered', 'trapped'], correct: 0 },
  { question: 'make a word using  "t, h, e, s, e"', options: ['sheet', 'shirts', 'tease'], correct: 0 },
  { question: 'make a word using  "i, t, e, m, s"', options: ['emits', 'timed', 'mints'], correct: 0 },
  { question: 'make a word using  "g, r, o, w, n"', options: ['wrong', 'growl', 'nordic'], correct: 0 },
  { question: 'make a word using  "s, e, c, r, e, t"', options: ['erects', 'reacts', 'streak'], correct: 0 },
  { question: 'make a word using  "s, e, r, v, a, n, t"', options: ['taverns', 'ventures', 'serpents'], correct: 0 },
  { question: 'make a word using  "s, i, l, e, n, c, e"', options: ['license', 'slices', 'sincere'], correct: 0 },
  { question: 'make a word using  "l, e, t, t, e, r, s"', options: ['settler', 'street', 'shelters'], correct: 0 },
  { question: 'make a word using  "s, u, p, e, r"', options: ['purse', 'repulse', 'reuse'], correct: 0 },
  { question: 'make a word using  "c, h, e, a, t"', options: ['teach', 'techie', 'reach'], correct: 0 },
  { question: 'make a word using  "p, i, e, c, e, s"', options: ['specie', 'pisces', 'stencil'], correct: 0 },
  { question: 'make a word using  "r, e, s, i, d, e, d "', options: ['desired', 'derided', 'esquire'], correct: 0 },
  { question: 'make a word using  "m, i, l, e, s"', options: ['smile', 'slide', 'davis'], correct: 0 },
  { question: 'make a word using  "a, b, c, s"', options: ['cabs', 'bash', 'caps'], correct: 0 },
  { question: 'make a word using  "d, e, m, o"', options: ['mode', 'done', 'mood'], correct: 0 },
  { question: 'make a word using  "s, h, o, t, g, u, n"', options: ['gunshot', 'showdown', 'nought'], correct: 0 },
  { question: 'make a word using  "t, e, a, r, s"', options: ['stare', 'street', 'reality'], correct: 0 },
  { question: 'make a word using  "m, i, r, a, c, l, e"', options: ['reclaim', 'circular', 'claimed'], correct: 0 },
  { question: 'make a word using  "d, a, i, r, y"', options: ['diary', 'rivaled', 'dearly'], correct: 0 },
  { question: 'make a word using  "a, l, o, r, s"', options: ['solar', 'royal', 'lasso'], correct: 0 },
  { question: 'make a word using  "s, t, r, e, a, m, s"', options: ['masters', 'matters', 'stressed'], correct: 0 },
  { question: 'make a word using  "m, a, t, t, r, e, s, s"', options: ['smartest', 'mastered', 'stardom'], correct: 0 },
  { question: 'make a word using  "s, l, i, g, h, t"', options: ['lights', 'tilted', 'guilds'], correct: 0 },
  { question: 'make a word using  "r, i, d, e, r"', options: ['drier', 'driven', 'redeem'], correct: 0 },
  { question: 'make a word using  "c, o, d, e, r, e, d"', options: ['decoder', 'recorded', 'cornered'], correct: 0 },
  { question: 'make a word using  "n, e, o"', options: ['one', 'ion', 'glitch'], correct: 0 },
  { question: 'make a word using  "e, n, t, r, a, p"', options: ['parent', 'pertinent', 'tamper'], correct: 0 },
  { question: 'means "clear"', options: ['transparent', 'sky', 'invade'], correct: 0 },
  { question: 'means "far"', options: ['remote', 'driven', 'reach'], correct: 0 },
  { question: 'means "guide"', options: ['lead', 'book', 'stream'], correct: 0 },
  { question: 'means "start"', options: ['begin', 'action', 'fresh'], correct: 0 },
  { question: 'means "chase"', options: ['pursuit', 'catch', 'grab'], correct: 0 },
  { question: 'means "fall"', options: ['autumn', 'slide', 'under'], correct: 0 },
  { question: 'means "fire"', options: ['shoot', 'pain', 'phaser'], correct: 0 },
  { question: 'means "credible"', options: ['believable', 'borrowed', 'appropriate'], correct: 0 },
  { question: 'means "fatal"', options: ['lethal', 'disappear', 'abrupt'], correct: 0 },
  { question: 'means "dull"', options: ['boring', 'motionless', 'locked'], correct: 0 },
  { question: 'opposite of "enemy"', options: ['ally', 'defeat', 'virtue'], correct: 0 },
  { question: 'opposite of "aware"', options: ['ignorant', 'open', 'neutral'], correct: 0 },
  { question: 'opposite of "negative"', options: ['positive', 'inanimate', 'arguable'], correct: 0 },
  { question: 'opposite of "keep"', options: ['give away', 'hold on', 'fort'], correct: 0 },
  { question: 'opposite of "quiet"', options: ['noisy', 'nose', 'normal'], correct: 0 },
  { question: 'opposite of "accelerate"', options: ['decelerate', 'decapitate', 'devastate'], correct: 0 },
  { question: 'one does not belong', options: ['terminator', 'dog', 'cat'], correct: 0 },
  { question: 'one does not belong', options: ['pear', 'celery', 'lettuce'], correct: 0 },
  { question: 'one does not belong', options: ['grandmother', 'father', 'uncle'], correct: 0 },
  { question: 'one does not belong', options: ['Michael Jackson', 'Justin Timberlake', 'Justin Bieber'], correct: 0 },
  { question: 'one does not belong', options: ['bacon', 'brussels sprout', 'broccoli'], correct: 0 },
  { question: 'one does not belong', options: ['jimmy page', 'john rambo', 'james bond'], correct: 0 },
  { question: 'one does not belong', options: ['awesomeness', 'gluttony', 'wrath'], correct: 0 },
  { question: 'one does not belong', options: ['one', '44', '66'], correct: 0 },
  { question: 'one does not belong', options: ['ratmouse', 'batman', 'catwoman'], correct: 0 },
  { question: 'one does not belong', options: ['submarine', 'cruiser', 'destroyer'], correct: 0 },
  { question: 'one does not belong', options: ['it\'s this one', 'not this', 'not this'], correct: 0 },
  { question: 'means "exaggeration"', options: ['overstatement', 'underline', 'point'], correct: 0 },
  { question: 'means "amazing"', options: ['astonishing', 'explosive', 'shiny'], correct: 0 },
  { question: 'means "fearless"', options: ['brave', 'scared', 'sneaky'], correct: 0 },
  { question: 'means "stop"', options: ['halt', 'hammertime', 'slow'], correct: 0 },
  { question: 'means "display"', options: ['show', 'flat', 'open'], correct: 0 },
  { question: 'means "scheme"', options: ['plan', 'play', 'theme'], correct: 0 },
  { question: 'means "catastrophe"', options: ['calamity', 'punishment', 'corpse'], correct: 0 },
  { question: 'means "important"', options: ['significant', 'sound', 'precise'], correct: 0 },
  { question: 'means "finite"', options: ['limited', 'inventory', 'endless'], correct: 0 },
  { question: 'means "unique"', options: ['singular', 'minimal', 'precise'], correct: 0 },
  { question: 'means "altered"', options: ['changed', 'punished', 'seen'], correct: 0 },
  { question: 'means "conserve"', options: ['save', 'spend', 'speak'], correct: 0 },
  { question: 'means "converse"', options: ['talk', 'save', 'change'], correct: 0 },
  { question: 'means "diction"', options: ['articulation', 'arthritis', 'artichoke'], correct: 0 },
  { question: 'means "fluent"', options: ['articulate', 'driven', 'artistry'], correct: 0 },
  { question: 'means "speedy"', options: ['fast', 'quirky', 'timeless'], correct: 0 },
  { question: 'means "trustworthy"', options: ['reliable', 'relinquished', 'resentful'], correct: 0 },
  { question: 'means "defend"', options: ['protect', 'attack', 'trap'], correct: 0 },
  { question: 'means "liberated"', options: ['free', 'fiery', 'fried'], correct: 0 },
  { question: 'means "useful"', options: ['beneficial', 'wasteful', 'new'], correct: 0 },
  { question: 'means "hazardous"', options: ['dangerous', 'cloudy', 'deceased'], correct: 0 },
  { question: 'opposite of "lifeless"', options: ['alive', 'quick', 'passive'], correct: 0 },
  { question: 'opposite of "boring"', options: ['exciting', 'fiery', 'massive'], correct: 0 },
  { question: 'opposite of "hard"', options: ['easy', 'stiff', 'bare'], correct: 0 },
  { question: 'opposite of "hostile"', options: ['friendly', 'smile', 'passionate'], correct: 0 },
  { question: 'opposite of "aggresive"', options: ['calm', 'sleepy', 'irritated'], correct: 0 },
  { question: 'opposite of "long"', options: ['abridged', 'enduring', 'stretching'], correct: 0 },
  { question: 'opposite of "smile"', options: ['frown', 'stare', 'sneeze'], correct: 0 },
  { question: 'opposite of "rich"', options: ['poor', 'taxed', 'citizen'], correct: 0 },
  { question: 'opposite of "last"', options: ['first', 'short', 'fun'], correct: 0 },
  { question: 'opposite of "give"', options: ['take', 'red pill', 'now'], correct: 0 },
  { question: 'opposite of "accept"', options: ['refuse', 'hold', 'included'], correct: 0 },
  { question: 'opposite of "always"', options: ['never', 'random', 'limitless'], correct: 0 },
  { question: 'opposite of "calm"', options: ['excited', 'bounced', 'elevator'], correct: 0 },
  { question: 'opposite of "find"', options: ['lose', 'feel', 'drop'], correct: 0 },
  { question: 'opposite of "maximum"', options: ['minimum', 'optimum', 'uber'], correct: 0 },
  { question: 'second line of a haiku has ___', options: ['7 syllables', '13 syllables', '5 syllables'], correct: 0 },
  { question: 'a constructed international language', options: ['esperanto', 'kebasish', 'chicat'], correct: 0 },
  { question: 'first line of a haiku has ___', options: ['5 syllables', '10 syllables', '7 syllables'], correct: 0 },
  { question: 'rhymes with "crime"', options: ['prime', 'scream', 'figure'], correct: 0 },
  { question: 'rhymes with "faster"', options: ['master', 'care', 'nostril'], correct: 0 },
  { question: 'rhymes with "blue"', options: ['glue', 'flee', 'fruit'], correct: 0 },
  { question: 'rhymes with "awesome"', options: ['possum', 'cushion', 'dreamer'], correct: 0 },
  { question: 'rhymes with "read"', options: ['feed', 'creep', 'steep'], correct: 0 },
  { question: 'rhymes with "fruit"', options: ['suit', 'seed', 'salt'], correct: 0 },
  { question: 'rhymes with "claim"', options: ['blame', 'charm', 'smile'], correct: 0 },
  { question: 'rhymes with "bliss"', options: ['kiss', 'fist', 'stressed'], correct: 0 },
  { question: 'rhymes with "face"', options: ['space', 'boss', 'moose'], correct: 0 },
  { question: 'rhymes with "chair"', options: ['stare', 'fail', 'brains'], correct: 0 },
  { question: 'rhymes with "style"', options: ['while', 'crime', 'kanye'], correct: 0 },
  { question: 'rhymes with "grace"', options: ['trace', 'fries', 'ella'], correct: 0 },
  { question: 'rhymes with "smarts"', options: ['hearts', 'maces', 'nerds'], correct: 0 },
  { question: 'rhymes with "prime"', options: ['crime', 'line', 'pristine'], correct: 0 },
  { question: 'rhymes with "rap"', options: ['tap', 'slack', 'snoop'], correct: 0 },
  { question: 'contains the letters "r, t, m"', options: ['rhythm', 'trapped', 'realm'], correct: 0 },
  { question: 'contains the letters "b, r, v"', options: ['beverage', 'brain', 'revered'], correct: 0 },
  { question: 'contains the letters "i, s, d"', options: ['disdain', 'significant', 'delightful'], correct: 0 },
  { question: 'contains the letters "u, a, n"', options: ['annual', 'underline', 'unwind'], correct: 0 },
  { question: 'contains the letters "i, r, c"', options: ['crime', 'record', 'creepy'], correct: 0 },
  { question: 'contains the letters "t, e, a"', options: ['reality', 'esteem', 'artistic'], correct: 0 },
  { question: 'contains the letters "m, l, n"', options: ['lemon', 'smile', 'linear'], correct: 0 },
  { question: 'contains the letters "d, r, e"', options: ['eradicate', 'excruciating', 'delighted'], correct: 0 },
  { question: 'contains the letters "y, i, n"', options: ['rainy', 'frankly', 'nyan'], correct: 0 },
  { question: 'contains the letters "b, u, t"', options: ['tub', 'tap', 'bun'], correct: 0 },
  { question: 'contains the letters "g, r, n"', options: ['wrong', 'gone', 'ripping'], correct: 0 },
  { question: 'contains the letters "t, r, l"', options: ['retail', 'troy', 'light'], correct: 0 },
  { question: 'contains the letters "l, s, r"', options: ['resale', 'retain', 'sorry'], correct: 0 },
  { question: 'contains the letters "t, i, f"', options: ['fifty', 'three', 'fine'], correct: 0 },
  { question: 'contains the letters "m, n, g"', options: ['gaming', 'ginger', 'menace'], correct: 0 },
  { question: 'contains the letters "m, t, r"', options: ['terminate', 'remembered', 'ricochet'], correct: 0 },
  { question: 'contains the letters "l, f, n"', options: ['nullify', 'fitness', 'laughter'], correct: 0 },
  { question: 'a word with no vowels', options: ['rhythm', 'slight', 'trouble'], correct: 0 },
  { question: 'a word with one vowel', options: ['wrong', 'fear', 'anguish'], correct: 0 },
  { question: 'a word with two vowels', options: ['fire', 'cut', 'spiteful'], correct: 0 },
  { question: 'a one syllable word', options: ['strength', 'fearless', 'charger'], correct: 0 },
  { question: 'a two syllable word', options: ['limit', 'fight', 'cat'], correct: 0 },
  { question: 'contraction of "you are"', options: ['you\'re', 'your', 'yogurt'], correct: 0 },
  { question: 'contraction of "there is"', options: ['there\'s', 'theirs', 'theresa'], correct: 0 },
  { question: 'plural of "you"', options: ['you', 'they', 'we'], correct: 0 },
  { question: 'plural of "sheep"', options: ['sheep', 'sheeps', 'herd'], correct: 0 },
  { question: 'plural of "plurality"', options: ['pluralities', 'plutorallies', 'plurals'], correct: 0 },
  { question: 'plural of "ball"', options: ['balls', 'ballies', 'balles'], correct: 0 },
  { question: 'plural of "goose"', options: ['geese', 'gooses', 'gooster'], correct: 0 },
  { question: 'singular of "mice"', options: ['mouse', 'moose', 'mices'], correct: 0 },
  { question: 'singular of "dice"', options: ['die', 'douse', 'dices'], correct: 0 },
  { question: 'the letter missing from "foregn"', options: ['i', 'h', 'y'], correct: 0 },
  { question: 'the letter missing from "stret"', options: ['e', 'r', 'n'], correct: 0 },
  { question: 'a young goat is called a ___', options: ['kid', 'boy', 'goatee'], correct: 0 },
  { question: 'a group of crows is called a ___', options: ['murder', 'massacre', 'nightmare'], correct: 0 },
  { question: 'a female deer is called a ___', options: ['doe', 'jane', 'dear'], correct: 0 },
  { question: 'a male llama is called a ___', options: ['llama', 'spitter', 'nazgul'], correct: 0 },
  { question: 'a male moose is called a ___', options: ['bull', 'cow', 'mouse'], correct: 0 },
  { question: 'contains the letters "t, i, l"', options: ['application', 'subliminal', 'promotion'], correct: 0 },
  { question: 'contains the letters "c, d, i"', options: ['idyllic', 'candle', 'decompose'], correct: 0 },
  { question: 'contains the letters "e, w, a"', options: ['whatever', 'whoever', 'wherever'], correct: 0 },
  { question: 'make a word using  "l, e, a, d, e, r"', options: ['dealer', 'ladder', 'realtor'], correct: 0 },
  { question: 'make a word using  "l, i, s, t, e, n"', options: ['silent', 'thistle', 'simple'], correct: 0 },
  { question: 'make a word using  "a, d, m, i, r, e, r"', options: ['married', 'dreamer', 'mirrored'], correct: 0 },
  { question: 'make a word using  "m, a, s, t, e, r"', options: ['stream', 'steer', 'stared'], correct: 0 },
  { question: 'make a word using  "s, t, e, a, l"', options: ['least', 'stare', 'later'], correct: 0 },
  { question: 'make a word using  "s, h, a, p, e"', options: ['phase', 'haters', 'heals'], correct: 0 },
  { question: 'rhymes with "diner"', options: ['minor', 'mordor', 'figured'], correct: 0 },
  { question: 'make a word using  "c, i, r, c, l, e"', options: ['cleric', 'critical', 'circus'], correct: 0 },
  { question: 'means "hidden"', options: ['concealed', 'displayed', 'apart'], correct: 0 },
  { question: 'means "help"', options: ['assist', 'cry', 'push'], correct: 0 },
  { question: 'means "similar"', options: ['akin', 'exact', 'mirror'], correct: 0 },
  { question: 'means "stable"', options: ['firm', 'ground', 'peaceful'], correct: 0 },
  { question: 'means "immortal"', options: ['deathless', 'highlander', 'strong'], correct: 0 },
  { question: 'a palindrome', options: ['rotator', 'delivered', 'detected'], correct: 0 },
  { question: 'a palindrome', options: ['now I won', 'name the man', 'is this it'], correct: 0 },
  { question: 'a palindrome', options: ['evil olive', 'do not nod', 'smart kids'], correct: 0 },
  { question: 'a palindrome', options: ['my gym', 'technologic', 'seven stars'], correct: 0 },
  { question: 'king of pop', options: ['Michael Jackson', 'Madonna', 'Lady Gaga'], correct: 0 },
  { question: 'king of rock and roll', options: ['Elvis Presley', 'Nickelback', 'Rihanna'], correct: 0 },
  { question: 'he composed "The Four Seasons"', options: ['A. Vivaldi', 'W. Mozart', 'Dr. Dre'], correct: 0 },
  { question: 'an 80s hit song', options: ['Take On Me', 'Kill The Batboy', 'Halftime'], correct: 0 },
  { question: 'an 80s hit song', options: ['Under Pressure', 'Under Ice', 'Under Fire'], correct: 0 },
  { question: 'a 70s hit song', options: ['Dancing Queen', 'Dancing Mice', 'Dancing Heat'], correct: 0 },
  { question: 'a 70s hit song', options: ['Imagine', 'Cruel summer', 'Vogue'], correct: 0 },
  { question: 'French singer and cultural icon', options: ['Edith Piaf', 'Nicolas Sarkozy', 'Asterix'], correct: 0 },
  { question: 'a 90s hit song', options: ['One', 'Let It B', 'Imagine'], correct: 0 },
  { question: 'a 60s hit song', options: ['She Loves You', 'She Loves It', 'Who Loves Her'], correct: 0 },
  { question: 'a 60s hit song', options: ['It\'s Not Unusual', 'Usually Not', 'Nothing Usual'], correct: 0 },
  { question: 'a song by Frank Sinatra', options: ['My Way', 'Let\'s Go New York', 'Whatever, yo'], correct: 0 },
  { question: 'a song by Madonna', options: ['Vogue', 'Let It Be', 'Bad'], correct: 0 },
  { question: 'a song by Michael Jackson', options: ['Beat It', 'Mad World', 'Pity Yourself'], correct: 0 },
  { question: 'a song by Elvis Presley', options: ['Heartbreak Hotel', 'Satistfaction', 'Respect'], correct: 0 },
  { question: 'a member of Dave Matthews Band', options: ['Dave Matthews', 'Dave Grohl', 'Dave Mustaine'], correct: 0 },
  { question: 'a song by The Beatles', options: ['Hey Jude', 'Hey Baby', 'Hey Girl'], correct: 0 },
  { question: 'a song by Justin Bieber', options: ['Never Say Never', 'Burn It All', 'Bad Pop'], correct: 0 },
  { question: 'a song by Queen', options: ['Killer Queen', 'Conformist Rhapsody', 'We Rock It'], correct: 0 },
  { question: 'a song by Abba', options: ['Dancing Queen', 'Mia Mia', 'One of Them'], correct: 0 },
  { question: 'a song by Pink Floyd', options: ['Money', 'Lies', 'Happiness'], correct: 0 },
  { question: 'a song by Metallica', options: ['Fade to Black', 'Gears of War', 'Madhouse'], correct: 0 },
  { question: 'lead vocalist of Queen', options: ['Freddie Mercury', 'Dave Mustaine', 'Barry Gibb'], correct: 0 },
  { question: 'lead vocalist of Led Zeppelin', options: ['Robert Plant', 'Jenny Page', 'John Bonham'], correct: 0 },
  { question: 'lead vocalist of Blondie', options: ['Debbie Harry', 'Justin Bieber', 'Madonna'], correct: 0 },
  { question: 'famous jazz trumpeter', options: ['Miles Davis', 'Ella Fitzgerald', 'Max Roach'], correct: 0 },
  { question: 'famous jazz singer', options: ['Etta James', 'Etta Candy', 'Etta May'], correct: 0 },
  { question: 'famous jazz singer', options: ['Ella Fitzgerald', 'Debbie Harry', 'Chad Kroeger'], correct: 0 },
  { question: 'famous jazz singer', options: ['Louis Armstrong', 'Luiz Armstrong', 'Louise Armstrong'], correct: 0 },
  { question: 'he composed "The Nutcracker"', options: ['P. Tchaikovsky', 'F. Mercury', 'J. Haydn'], correct: 0 },
  { question: 'famous rapper', options: ['Jay Z', 'May C', 'Kay T'], correct: 0 },
  { question: 'famous guitarist', options: ['Eric Clapton', 'Richard Roll', 'Lars Ulrich'], correct: 0 },
  { question: 'famous guitarist', options: ['David Gilmour', 'David Beckham', 'David Hume'], correct: 0 },
  { question: 'famous guitarist', options: ['Jimmy Page', 'Lars Umlaut', 'Johnny Napalm'], correct: 0 },
  { question: 'British rock band', options: ['Oasis', 'Desert', 'Water'], correct: 0 },
  { question: 'Canadian rock band', options: ['Nickelback', 'The Worsts', 'Burn \'em'], correct: 0 },
  { question: 'German rock band', options: ['Rammstein', 'Rich Rohl', 'Madson'], correct: 0 },
  { question: 'Australian rock band', options: ['AC/DC', 'DC/AC', 'AD/HD'], correct: 0 },
  { question: 'British singer', options: ['Chris Martin', 'D. Hubbins', 'J. Clement'], correct: 0 },
  { question: 'part of the Woodstock \'69 line-up', options: ['Santana', 'Led zeppelin', 'The beatles'], correct: 0 },
  { question: 'he composed "The Barber of Seville"', options: ['G. Rossini', 'I. Padrino', 'M. Donna'], correct: 0 },
  { question: 'an album by The Beatles', options: ['The Beatles', 'Black Hole', 'New Grounds'], correct: 0 },
  { question: 'an album by Pearl Jam', options: ['Ten', 'Book of Faces', 'Your Space'], correct: 0 },
  { question: '"Hotel California" is a song by ___', options: ['Eagles', 'Bee Gees', 'The Beach Boys'], correct: 0 },
  { question: '"Bohemian Rhapsody" is a song by ___', options: ['Queen', 'Kings of Leon', 'Megadeth'], correct: 0 },
  { question: '"Smells Like Teen Spirit" is a song by ___', options: ['Nirvana', 'Van halen', 'Bon Jovi'], correct: 0 },
  { question: '"London Calling" is a song by ___', options: ['The Clash', 'The Police', 'The Telephone'], correct: 0 },
  { question: 'famous J-Pop artist', options: ['Hikaru Utada', 'Ichiro Suziki', 'Hayao Miyazaki'], correct: 0 },
  { question: '"No Woman No Cry" is a song by ___', options: ['Bob Marley', 'Buddy Holly', 'Aerosmith'], correct: 0 },
  { question: '"Born To Be Wild" is a song by ___', options: ['Steppenwolf', 'Jimi Hendrix', 'Johnny Cash'], correct: 0 },
  { question: 'won an Oscar in 1998', options: ['Gywneth Paltrow', 'Meryl Streep', 'Tom Hanks'], correct: 0 },
  { question: 'won an Oscar in 2005', options: ['George Clooney', 'Joaquin Phoenix', 'Felicity Huffman'], correct: 0 },
  { question: 'won an Oscar in 1966', options: ['Elizabeth Taylor', 'Jack Nicholson', 'Michael Caine'], correct: 0 },
  { question: 'won an Oscar in 2008', options: ['Sean Penn', 'Brad Pitt', 'Meryl Streep'], correct: 0 },
  { question: 'won the Best Actor Oscar in 1975', options: ['Jack Nicholson', 'Al Pacino', 'Yul Brynner'], correct: 0 },
  { question: 'won the Best Actor Oscar in 1954', options: ['Marlon Brando', 'Al Pacino', 'Gene Hackman'], correct: 0 },
  { question: 'starred in The Lord Of The Rings', options: ['Elijah Wood', 'Meryl Streep', 'Ron Perlman'], correct: 0 },
  { question: 'never played Superman', options: ['Brad Pitt', 'Christopher Reeve', 'Brandon Routh'], correct: 0 },
  { question: 'starred along Tom Cruise', options: ['Val Kilmer', 'Al Pacino', 'Tommy Lee Jones'], correct: 0 },
  { question: 'starred along Anthony Hopkins', options: ['Jodie Foster', 'Wesley Snipes', 'Kevin Bacon'], correct: 0 },
  { question: 'starred along Julia Roberts', options: ['Richard Gere', 'Chris Rock', 'Johnny Depp'], correct: 0 },
  { question: 'fictional character also known as Smeagol', options: ['Gollum', 'Precious Sam', 'Darth Frodo'], correct: 0 },
  { question: 'not a Sith Lord', options: ['Darth Saber', 'Darth Vader', 'Darth Maul'], correct: 0 },
  { question: 'a Sith Lord', options: ['Darth Sidious', 'Darth Mouth', 'Darth Thrash'], correct: 0 },
  { question: 'never played James Bond', options: ['Michael Jackson', 'Sean Connery', 'Pierce Brosnon'], correct: 0 },
  { question: 'fictional robot from the future', options: ['The Terminator', 'Vin Diesel', 'Casper'], correct: 0 },
  { question: 'fat kid in South Park', options: ['Eric Cartman', 'Big Bones', 'Bart Simpson'], correct: 0 },
  { question: 'Homer\'s last name in The Simpsons', options: ['Simpson', 'Simpsons', 'Simpleton'], correct: 0 },
  { question: 'Woody Allen wrote and directed ___', options: ['Annie Hall', 'Antz', 'Animal House'], correct: 0 },
  { question: 'never won an Oscar', options: ['Will Smith', 'Meryl Streep', 'Cuba Gooding Jr.'], correct: 0 },
  { question: 'The Terminator tries to terminate ___', options: ['John Connor', 'John Nash', 'Edward Cullen'], correct: 0 },
  { question: 'played Edward Cullen in Twilight', options: ['R. Pattinson', 'B. Shame', 'U. Madbrough'], correct: 0 },
  { question: 'Rocky II takes place in ___', options: ['Philadelphia', 'Moscow', 'Rocky Mountains'], correct: 0 },
  { question: 'Don Corleone\'s son in The Godfather', options: ['Michael', 'Sergio', 'Christian'], correct: 0 },
  { question: 'his sword is called Sting', options: ['B. Baggins', 'E. Cullen', 'J. Bieber'], correct: 0 },
  { question: 'Marcellus Wallace looks like ___', options: ['Marcellus Wallace', 'a lady', 'Vincent Vega'], correct: 0 },
  { question: 'pick the better actress', options: ['Madonna', 'Jack Nicholson', 'Al Pacino'], correct: 0 },
  { question: 'Bruce Wayne is ___', options: ['Batman', 'Hulk', 'Superman'], correct: 0 },
  { question: 'Clark Kent is ___', options: ['Superman', 'Batman', 'Aquaman'], correct: 0 },
  { question: 'Luke Skywalker\'s grandfather\'s son', options: ['Darth Vader', 'Palpatine', 'C3P0'], correct: 0 },
  { question: 'a minute has ___ seconds', options: ['60', '10', '100'], correct: 0 },
  { question: 'four times twenty plus ten', options: ['90', '80', '110'], correct: 0 },
  { question: '4+20-14', options: ['10', '8', '14'], correct: 0 },
  { question: 'five times zero times two', options: ['0', '2', '10'], correct: 0 },
  { question: '4 is ___ times 2', options: ['2', '4', '1'], correct: 0 },
  { question: 'four squared plus four', options: ['20', '64', '48'], correct: 0 },
  { question: 'negative five plus nine', options: ['4', '-14', '-4'], correct: 0 },
  { question: 'zero divided by one', options: ['0', '1', '3141592'], correct: 0 },
  { question: '1+1+1x0', options: ['2', '0', '1'], correct: 0 },
  { question: 'the number of letters in "apple"', options: ['5', '3', '1976'], correct: 0 },
  { question: 'the number of letters in "four"', options: ['4', '5', '6'], correct: 0 },
  { question: '2222+3333', options: ['5555', '5550', '5600'], correct: 0 },
  { question: '9.81+0.19', options: ['10', '11', '9.99'], correct: 0 },
  { question: '4 followed by 0', options: ['40', '2500', '411'], correct: 0 },
  { question: '9 followed by 1', options: ['91', '929', '199'], correct: 0 },
  { question: 'not an integer', options: ['3.4', '34', '4'], correct: 0 },
  { question: 'an integer', options: ['8', '8.8', '8.88'], correct: 0 },
  { question: 'square root of nine', options: ['3', '81', '9'], correct: 0 },
  { question: 'square root of four', options: ['2', '1', '4'], correct: 0 },
  { question: 'three squared plus four', options: ['13', '9', '18'], correct: 0 },
  { question: '100 in roman numerals', options: ['c', 'k', 'x'], correct: 0 },
  { question: 'number system with a base of two', options: ['binary', 'decimal', 'hexadecimal'], correct: 0 },
  { question: 'number system with a base of ten', options: ['decimal', 'binary', 'octal'], correct: 0 },
  { question: '3 in base 2', options: ['11', '33', '44'], correct: 0 },
  { question: '5 in base 2', options: ['101', '112', '1'], correct: 0 },
  { question: '7 in base 8', options: ['7', '16', '66'], correct: 0 },
  { question: '88 in base 4', options: ['1120', '1234', '22227'], correct: 0 },
  { question: 'an octagon has ___ sides', options: ['8', '4', '16'], correct: 0 },
  { question: 'a square has ___ sides', options: ['4', '3', '5'], correct: 0 },
  { question: '30 divided by 0.5', options: ['60', '15', '45'], correct: 0 },
  { question: '100 divided by 0.8', options: ['125', '180', '60'], correct: 0 },
  { question: '99 divided by 0.9', options: ['110', '121', '90'], correct: 0 },
  { question: '1100 times 1.2', options: ['1320', '990', '1.32'], correct: 0 },
  { question: 'a billion has ___ zeros', options: ['9', '8', '12'], correct: 0 },
  { question: 'a million has ___ zeros', options: ['6', '9', '12'], correct: 0 },
  { question: '1+9+7+6', options: ['23', '1977', '19'], correct: 0 },
  { question: '1+9+9+4', options: ['23', '24', '21'], correct: 0 },
  { question: '1+9+8+0', options: ['18', '16', '27'], correct: 0 },
  { question: 'number of faces on a cube', options: ['6', '9', '12'], correct: 0 },
  { question: 'number of faces on a cylinder', options: ['3', '1', '271'], correct: 0 },
  { question: 'pi is a(n) ___ number', options: ['irrational', 'rational', 'delicious'], correct: 0 },
  { question: '8/4/1/2', options: ['1', '2', '4'], correct: 0 },
  { question: '16/4/2/1', options: ['2', '4', '8'], correct: 0 },
  { question: '21+42-1', options: ['62', '66', '44'], correct: 0 },
  { question: '1+2+3+4+5', options: ['15', '10', '21'], correct: 0 },
  { question: '3-2+1-2+2', options: ['2', '1', '0'], correct: 0 },
  { question: '4+4+5x0', options: ['8', '13', '18'], correct: 0 },
  { question: '12+11+13', options: ['36', '23', '39'], correct: 0 },
  { question: '4999.18-0.18', options: ['4999', '5000', '5001'], correct: 0 },
  { question: 'seven plus eleven', options: ['18', '117', '19'], correct: 0 },
  { question: 'nine times nine plus eleven', options: ['92', '100', '99'], correct: 0 },
  { question: '9x8x7x0-5', options: ['-5', '0', '75'], correct: 0 },
  { question: 'two times zero plus one', options: ['1', '12', '3'], correct: 0 },
  { question: '5+4+6+10', options: ['25', '40', '24'], correct: 0 },
  { question: '1+2+4+8', options: ['15', '13', '17'], correct: 0 },
  { question: '44+66', options: ['110', '100', '120'], correct: 0 },
  { question: '77+23', options: ['100', '90', '93'], correct: 0 },
  { question: '111+99', options: ['210', '200', '211'], correct: 0 },
  { question: 'square root of sixteen', options: ['4', '8', '2'], correct: 0 },
  { question: 'cube root of 64', options: ['4', '16', '8'], correct: 0 },
  { question: 'cube root of 125', options: ['5', '25', '15'], correct: 0 },
  { question: 'cube root of 27', options: ['3', '9', '27'], correct: 0 },
  { question: 'the number of months in six years', options: ['72', '25', '6'], correct: 0 },
  { question: 'the number of weeks in a month', options: ['4', '52', '7'], correct: 0 },
  { question: 'the number of days in a week', options: ['7', '30', '12'], correct: 0 },
  { question: 'the number of digits in 456', options: ['3', '2', '1'], correct: 0 },
  { question: 'the number of digits in 4.44', options: ['3', '2', '4'], correct: 0 },
  { question: 'half a dozen times eleven', options: ['66', '121', '77'], correct: 0 },
  { question: 'one less than two', options: ['1', '3', '21'], correct: 0 },
  { question: 'two more than one', options: ['3', '6', '1'], correct: 0 },
  { question: 'a number between 444 and 555', options: ['499', '577', '399'], correct: 0 },
  { question: 'a number between 195 and 333', options: ['330', '388', '169'], correct: 0 },
  { question: 'a number between 75 and 999999', options: ['100000', '72', '2566624'], correct: 0 },
  { question: 'a number between 1 and 6', options: ['5', '61', '7'], correct: 0 },
  { question: 'a number between 4 and 5', options: ['4.5', '5.4', '3.4'], correct: 0 },
  { question: '88/8/11', options: ['1', '8', '11'], correct: 0 },
  { question: '25-5-5-5-5', options: ['5', '0', '15'], correct: 0 },
  { question: '66-65+1x0', options: ['1', '2', '3'], correct: 0 },
  { question: '51+51+49', options: ['151', '153', '147'], correct: 0 },
  { question: '14+13+12+11', options: ['50', '61', '40'], correct: 0 },
  { question: '661-444', options: ['217', '127', '227'], correct: 0 },
  { question: '91+92-4', options: ['179', '178', '177'], correct: 0 },
  { question: '911+118', options: ['1029', '1119', '1099'], correct: 0 },
  { question: '468+864', options: ['1332', '1442', '1342'], correct: 0 },
  { question: '77+99', options: ['176', '117', '177'], correct: 0 },
  { question: '4.66+1.34', options: ['6', '6.6', '6.67'], correct: 0 },
  { question: '2012-1982', options: ['30', ':(', '20'], correct: 0 },
  { question: '99999+1', options: ['100000', '10000', '100001'], correct: 0 },
  { question: '16/4x1+1', options: ['5', '6', '7'], correct: 0 },
  { question: '81+18', options: ['99', '98', '109'], correct: 0 },
  { question: 'the number of months in six months', options: ['6', '42', '12'], correct: 0 },
  { question: 'the average of 6 and 12', options: ['9', '6', '18'], correct: 0 },
  { question: 'the average of 1, 2 and 3', options: ['2', '6', '3'], correct: 0 },
  { question: 'the average of 8 and 88', options: ['48', '11', '40'], correct: 0 },
  { question: 'the average of 1 and 99', options: ['50', '49', '48'], correct: 0 },
  { question: 'the average of 4 and 100', options: ['52', '44', '72'], correct: 0 },
  { question: 'the average of 2 and 12', options: ['7', '5', '6'], correct: 0 },
  { question: 'the average of 3 and 41', options: ['22', '19', '24'], correct: 0 },
  { question: 'the average of 802 and 208', options: ['505', '355', '555'], correct: 0 },
  { question: 'the average of 111 and 221', options: ['166', '156', '332'], correct: 0 },
  { question: 'five times four times five', options: ['100', '80', '60'], correct: 0 },
  { question: '499+130', options: ['629', '529', '639'], correct: 0 },
  { question: '3+3+13-1', options: ['18', '21', '24'], correct: 0 },
  { question: '2/2/1/1', options: ['1', '2', '0.5'], correct: 0 },
  { question: '3+1+4', options: ['8', '9', '10'], correct: 0 },
  { question: '8+5+7-11', options: ['9', '11', '33'], correct: 0 },
  { question: '4200/300', options: ['14', '140', '144'], correct: 0 },
  { question: 'negative nine plus nineteen', options: ['10', '9', '19'], correct: 0 },
  { question: 'the number of fingers on four hands', options: ['20', '44', '60'], correct: 0 },
  { question: 'negative three squared', options: ['9', '-3', '0'], correct: 0 },
  { question: 'one plus another one', options: ['2', '1', '0'], correct: 0 },
  { question: 'ten divided by half', options: ['20', '10', '0'], correct: 0 },
  { question: '33/1.1', options: ['30', '36', '11'], correct: 0 },
  { question: '422+42+4.2', options: ['468.2', '466.2', '486.2'], correct: 0 },
  { question: '10-99-1+100', options: ['10', '11', '89'], correct: 0 },
  { question: '10-9+8-7', options: ['2', '0', '-2'], correct: 0 },
  { question: '1.11x300', options: ['333', '311', '133'], correct: 0 },
  { question: 'giga stands for', options: ['1 billion', '1 million', '100 million'], correct: 0 },
  { question: 'total interior angles of a triangle', options: ['180', '360', '270'], correct: 0 },
  { question: 'total interior angles of a square', options: ['360', '180', '480'], correct: 0 },
  { question: '1 times 2 times 4 times 3', options: ['24', '12', '16'], correct: 0 },
  { question: '30 multiplied by 0.3', options: ['9', '90', '18'], correct: 0 },
  { question: '55/11/2x2', options: ['5', '5.5', '11'], correct: 0 },
  { question: '888-444-44', options: ['400', '440', '396'], correct: 0 },
  { question: '412+214-1', options: ['625', '445', '665'], correct: 0 },
  { question: '4.1111-1', options: ['3.1111', '3.1', '4.1111'], correct: 0 },
  { question: 'the number of letters in "five"', options: ['4', '5', '9'], correct: 0 },
  { question: 'remainder of 10 divided by 8', options: ['2', '1', '1.25'], correct: 0 },
  { question: 'remainder of 55 divided by 6', options: ['1', '5', '3'], correct: 0 },
  { question: 'remainder of 22 divided by 11', options: ['0', '2', '1'], correct: 0 },
  { question: 'remainder of 99 divided by 44', options: ['11', '2', '5'], correct: 0 },
  { question: 'remainder of 99 divided by 97', options: ['2', '1', '98'], correct: 0 },
  { question: 'Twenty percent of twenty', options: ['4', '5', '10'], correct: 0 },
  { question: 'Forty five percent of 200', options: ['90', '180', '120'], correct: 0 },
  { question: '33% of 1500', options: ['495', '500', '455'], correct: 0 },
  { question: '81% of 200', options: ['162', '188', '119'], correct: 0 },
  { question: '110% of 110', options: ['121', '111', '132'], correct: 0 },
  { question: '1/(1x2/2)', options: ['1', '2', '0'], correct: 0 },
  { question: 'Sixty one percent of one', options: ['0.61', '6.1', '0.39'], correct: 0 },
  { question: '8 is the square root of ___', options: ['64', '4', '72'], correct: 0 },
  { question: '13 is the square root of ___', options: ['169', '39', '139'], correct: 0 },
  { question: '6 is the cube root of ___', options: ['216', '96', '36'], correct: 0 },
  { question: '779-(-4/2)', options: ['781', '777', '333'], correct: 0 },
  { question: 'the first number after one', options: ['2', '3', '5'], correct: 0 },
  { question: '33 times 0.30', options: ['9.9', '11', '10'], correct: 0 },
  { question: '67.33+33.67', options: ['101', '110', '100'], correct: 0 },
  { question: '44-22-11+33', options: ['44', '33', '55'], correct: 0 },
  { question: '12 multiplied by itself', options: ['144', '124', '132'], correct: 0 },
  { question: '66246 divided by itself', options: ['1', '33123', '2'], correct: 0 },
  { question: '5=3+1+___', options: ['1', '5', '0'], correct: 0 },
  { question: '10+9+8-7', options: ['20', '11', '21'], correct: 0 },
  { question: '74+19', options: ['93', '91', '97'], correct: 0 },
  { question: '5-2-3-4+6', options: ['2', '0', '8'], correct: 0 },
  { question: 'two minus two hundred', options: ['-198', '202', '198'], correct: 0 },
  { question: '99/33/3/2', options: ['0.5', '1', '1.5'], correct: 0 },
  { question: 'fifteen squared', options: ['225', '175', '75'], correct: 0 },
  { question: '3333/2', options: ['1666.5', '1665.5', '1666.6'], correct: 0 },
  { question: 'eleven times thirteen', options: ['143', '131', '123'], correct: 0 },
  { question: '84+333', options: ['417', '447', '397'], correct: 0 },
  { question: '(8.1-0.1)x2', options: ['16', '16.2', '4.4'], correct: 0 },
  { question: 'the number of letters in "alphabet"', options: ['8', '29', '7'], correct: 0 },
  { question: 'negative seventeen squared', options: ['289', '-34', '249'], correct: 0 },
  { question: 'four times cube root of 64', options: ['16', '8', '4'], correct: 0 },
  { question: '996/4', options: ['249', '224', '199'], correct: 0 },
  { question: 'a number between 55.6 and 55.7', options: ['55.69', '55.71', '5.563'], correct: 0 },
  { question: 'your age plus 16.7 minus your age', options: ['16.7', '0', '-16.7'], correct: 0 },
  { question: '808+1200', options: ['2008', '2208', '2088'], correct: 0 },
  { question: 'absolute value of 99', options: ['99', '-99', '0'], correct: 0 },
  { question: 'absolute value of -0.8', options: ['0.8', '8', '-0.8'], correct: 0 },
  { question: '125/86x43/0.5', options: ['125', '1', '250'], correct: 0 },
  { question: 'the number of weeks in a day', options: ['1/7', '7', '0.15'], correct: 0 },
  { question: 'Fifty two plus five squared', options: ['77', '57', '75'], correct: 0 },
  { question: 'smaller than the others', options: ['199+44', '1999-555', '101+200'], correct: 0 },
  { question: 'smaller than the others', options: ['555-505', '155-55', '55.55'], correct: 0 },
  { question: 'larger than the others', options: ['2', '543-544', '3/4+1'], correct: 0 },
  { question: 'Norwegian flag has this color', options: ['blue', 'green', 'black'], correct: 0 },
  { question: 'Turkish flag has this color', options: ['red', 'blue', 'turquoise'], correct: 0 },
  { question: 'Ukranian flag has this color', options: ['blue', 'red', 'orange'], correct: 0 },
  { question: 'Canadian flag has this color', options: ['red', 'yellow', 'blue'], correct: 0 },
  { question: 'Brazilian flag has this color', options: ['blue', 'red', 'white'], correct: 0 },
  { question: 'Chinese flag has this color', options: ['red', 'magenta', 'orange'], correct: 0 },
  { question: 'Nigerian flag has this color', options: ['green', 'yellow', 'black'], correct: 0 },
  { question: 'Russian flag has this color', options: ['white', 'yellow', 'green'], correct: 0 },
  { question: 'Polish flag has this color', options: ['red', 'blue', 'green'], correct: 0 },
  { question: 'Tunisian flag has this symbol', options: ['crescent', 'cross', 'sun'], correct: 0 },
  { question: 'Uruguayan flag has this symbol', options: ['sun', 'cross', 'asteroid'], correct: 0 },
  { question: 'Guatemalan flag has this symbol', options: ['bird', 'bear', 'bison'], correct: 0 },
  { question: 'Angolan flag has this symbol', options: ['machete', 'bird', 'dinosaur'], correct: 0 },
  { question: 'Greek flag has this symbol', options: ['cross', 'branch', 'ipad'], correct: 0 },
  { question: 'Azerbaijani flag has this symbol', options: ['star', 'bird', 'shield'], correct: 0 },
  { question: 'Turkish flag has this symbol', options: ['star', 'lion', 'dragon'], correct: 0 },
  { question: 'Bhutanese flag has this symbol', options: ['dragon', 'eagle', 'shield'], correct: 0 },
  { question: 'German flag has ___', options: ['3 colors', '2 colors', '13 colors'], correct: 0 },
  { question: 'Ukranian flag has ___', options: ['2 colors', '3 colors', '4 colors'], correct: 0 },
  { question: 'South Korean flag has ___', options: ['4 colors', '3 colors', '42 colors'], correct: 0 },
  { question: 'a neighbor of France', options: ['Switzerland', 'Portugal', 'Austria'], correct: 0 },
  { question: 'a neighbor of Austria', options: ['Hungary', 'Belgium', 'USA'], correct: 0 },
  { question: 'a neighbor of Bulgaria', options: ['Turkey', 'Ukraine', 'China'], correct: 0 },
  { question: 'a neighbor of Turkey', options: ['Greece', 'Turkmenistan', 'India'], correct: 0 },
  { question: 'a neighbor of Chile', options: ['Bolivia', 'Paraguay', 'Kazakhstan'], correct: 0 },
  { question: 'a neighbor of Malaysia', options: ['Thailand', 'New Zealand', 'China'], correct: 0 },
  { question: 'a neighbor of South Africa', options: ['Zimbabwe', 'Angola', 'Mars'], correct: 0 },
  { question: 'a neighbor of Libya', options: ['Sudan', 'Israel', 'Finland'], correct: 0 },
  { question: 'a neighbor of Oman', options: ['Yemen', 'Iraq', 'Japan'], correct: 0 },
  { question: 'a neighbor of Estonia', options: ['Latvia', 'Lithuania', 'Brazil'], correct: 0 },
  { question: 'a neighbor of Kazakhstan', options: ['China', 'Vatican', 'Iran'], correct: 0 },
  { question: 'a neighbor of Sudan', options: ['Egypt', 'Nigeria', 'Morocco'], correct: 0 },
  { question: 'a neighbor of Israel', options: ['Syria', 'Iraq', 'Italy'], correct: 0 },
  { question: 'a neighbor of Pakistan', options: ['Iran', 'Russua', 'Kazakhstan'], correct: 0 },
  { question: 'a neighbor of Bangladesh', options: ['India', 'Pakistan', 'Indonesia'], correct: 0 },
  { question: 'not a neighbor of Paraguay', options: ['Narnia', 'Argentina', 'Brazil'], correct: 0 },
  { question: 'not a neighbor of Norway', options: ['South Africa', 'Russia', 'Sweden'], correct: 0 },
  { question: 'not a neighbor of Peru', options: ['Paraguay', 'Chile', 'Colombia'], correct: 0 },
  { question: 'not a neighbor of Spain', options: ['Sweden', 'Portugal', 'France'], correct: 0 },
  { question: 'Buckingham Palace is in', options: ['London', 'Manchester', 'Liverpool'], correct: 0 },
  { question: 'the capital of Malta', options: ['Valetta', 'Martha', 'Rohan'], correct: 0 },
  { question: 'the capital of Ecuador', options: ['Quito', 'Texas', 'Manta'], correct: 0 },
  { question: 'the capital of Kenya', options: ['Nairobi', 'Niobe', 'Mombasa'], correct: 0 },
  { question: 'the capital of Finland', options: ['Helsinki', 'Thor', 'Turku'], correct: 0 },
  { question: 'the capital of Italy', options: ['Rome', 'Monte Carlo', 'Madrid'], correct: 0 },
  { question: 'the capital of China', options: ['Beijing', 'Tokyo', 'Jackie Chan'], correct: 0 },
  { question: 'the capital of Turkey', options: ['Ankara', 'Istanbul', 'Athens'], correct: 0 },
  { question: 'the capital of Austria', options: ['Vienna', 'Venice', 'Vancouver'], correct: 0 },
  { question: 'the capital of Argentina', options: ['Buenos Aires', 'Santiago', 'Kiwingston'], correct: 0 },
  { question: 'currency of Estonia', options: ['Euro', 'Lira', 'Peipa'], correct: 0 },
  { question: 'the largest ocean', options: ['Pacific', 'Atlantic', 'Indian'], correct: 0 },
  { question: 'the Thames flows through', options: ['London', 'Paris', 'Belgrade'], correct: 0 },
  { question: 'the smallest ocean', options: ['Arctic', 'Indian', 'Southern'], correct: 0 },
  { question: 'largest country by area', options: ['Russia', 'China', 'Canada'], correct: 0 },
  { question: 'smallest country by area', options: ['Vatican', 'Monaco', 'Narnia'], correct: 0 },
  { question: 'third highest mountain in the world', options: ['Kangchenjunga', 'Himalchuli', 'Heibro'], correct: 0 },
  { question: 'the national internet domain is .al', options: ['Albania', 'Alabama', 'Algeria'], correct: 0 },
  { question: 'the national internet domain is .ch', options: ['Switzerland', 'China', 'Chihuahua'], correct: 0 },
  { question: 'the national internet domain is .es', options: ['Spain', 'Estonia', 'Sparta'], correct: 0 },
  { question: 'the internet domain of Finland', options: ['.fi', '.fin', '.fnd'], correct: 0 },
  { question: 'the internet domain of South africa', options: ['.za', '.ya', '.so'], correct: 0 },
  { question: 'the internet domain of Portugal', options: ['.pt', '.pg', '.por'], correct: 0 },
  { question: 'the internet domain of Indonesia', options: ['.id', '.in', '.io'], correct: 0 },
  { question: 'Great Victoria Desert is in', options: ['Australia', 'Russia', 'Tatooine'], correct: 0 },
  { question: 'Karakum Desert is in', options: ['Turkmenistan', 'Uzbekistan', 'Kurast'], correct: 0 },
  { question: 'Simpson Desert is in', options: ['Australia', 'Russia', 'Canada'], correct: 0 },
  { question: 'Bhutan is in ___', options: ['Asia', 'Africa', 'another castle'], correct: 0 },
  { question: 'Madagascar is ___', options: ['an island', 'a city', 'a continent'], correct: 0 },
  { question: 'Not a city in Russia', options: ['Anton', 'Kazan', 'St. Petersburg'], correct: 0 },
  { question: 'Volga River flows through', options: ['Russia', 'Sweden', 'Italy'], correct: 0 },
  { question: 'a city in Russia', options: ['Kazan', 'Iratsburg', 'Kunayeville'], correct: 0 },
  { question: 'a country in Africa', options: ['Chad', 'Matt', 'Smith'], correct: 0 },
  { question: 'a country in South America', options: ['Suriname', 'Burundi', 'Andorra'], correct: 0 },
  { question: 'a country in Asia', options: ['Jordan', 'Ukraine', 'Suriname'], correct: 0 },
  { question: 'not a country in Europe', options: ['Angola', 'Malta', 'Albania'], correct: 0 },
  { question: 'the larger country by area', options: ['Canada', 'China', 'Brazil'], correct: 0 },
  { question: 'the smaller country by area', options: ['India', 'Australia', 'Brazil'], correct: 0 },
  { question: 'an archipelago country', options: ['Phillipines', 'Nicaragua', 'Serbia'], correct: 0 },
  { question: 'chain or cluster of islands', options: ['archipelago', 'megalopolis', 'aquifer'], correct: 0 },
  { question: 'a landlocked country', options: ['Bhutan', 'Germany', 'Mexico'], correct: 0 },
  { question: 'not a landlocked country', options: ['Romania', 'Hungary', 'Armenia'], correct: 0 },
  { question: 'closest to the equator', options: ['India', 'Italy', 'Egypt'], correct: 0 },
  { question: '34th parallel north passes through ___', options: ['Japan', 'Russia', 'Australia'], correct: 0 },
  { question: '24th parallel south passes through ___', options: ['Australia', 'Russia', 'France'], correct: 0 },
  { question: '11th parallel north passes through ___', options: ['Colombia', 'Russia', 'South Korea'], correct: 0 },
  { question: '55th meridian west passes through ___', options: ['Brazil', 'Peru', 'USA'], correct: 0 },
  { question: '114th meridian east passes through ___', options: ['Indonesia', 'Pakistan', 'Japan'], correct: 0 },
  { question: 'the equator passes through ___', options: ['Argentina', 'USA', 'Paraguay'], correct: 0 },
  { question: '1988 Olympic Games host city', options: ['Seoul', 'Atlanta', 'Mexico City'], correct: 0 },
  { question: 'not an Olympic Games host city', options: ['Gotham', 'Athens', 'Amsterdam'], correct: 0 },
  { question: 'Machu Picchu is located in ___', options: ['Peru', 'Colombia', 'Paraguay'], correct: 0 },
  { question: 'a type of dog breed', options: ['Newfoundland', 'Chikita', 'Skubi'], correct: 0 },
  { question: 'population is more than 10 million', options: ['Istanbul', 'Switzerland', 'Chicago'], correct: 0 },
  { question: 'population is more than 9 million', options: ['Belgium', 'Swizterland', 'Denmark'], correct: 0 },
  { question: 'population is less than 33 million', options: ['Texas', 'Turkey', 'Tanzania'], correct: 0 },
  { question: 'the capital of Venezuela', options: ['Caracas', 'Maracaibo', 'Maracay'], correct: 0 },
  { question: 'the city further north', options: ['Rome', 'Cairo', 'Istanbul'], correct: 0 },
  { question: 'the city further south', options: ['Osaka', 'Seoul', 'Tokyo'], correct: 0 },
  { question: 'larger state by area', options: ['Wyoming', 'Utah', 'Nebraska'], correct: 0 },
  { question: 'larger state by population', options: ['Florida', 'Illinois', 'North Dakota'], correct: 0 },
  { question: 'city further north', options: ['Dakar', 'Kuala Lumpur', 'Bogota'], correct: 0 },
  { question: 'city further south', options: ['Bangkok', 'Dubai', 'Cancun'], correct: 0 },
  { question: 'larger country by population', options: ['Indonesia', 'Malaysia', 'Canada'], correct: 0 },
  { question: 'smaller country by population', options: ['Norway', 'Spain', 'Italy'], correct: 0 },
  { question: 'smaller country by area', options: ['Portugal', 'USA', 'Argentina'], correct: 0 },
  { question: 'smaller country by population', options: ['Israel', 'Kazakhstan', 'Vietnam'], correct: 0 },
  { question: '"Live free or die" on the license plate', options: ['New Hampshire', 'Montana', 'Texas'], correct: 0 },
  { question: 'Grand Canyon is in ___', options: ['Arizona', 'Colorado', 'New Hampshire'], correct: 0 },
  { question: 'Hagia Sofia is in ___', options: ['Istanbul', 'Athens', 'Budapest'], correct: 0 },
  { question: 'Waikiki Beach is in ___', options: ['Honolulu', 'Kingston', 'San Juan'], correct: 0 },
  { question: 'not a city in Canada', options: ['Sorritown', 'Hamilton', 'Calgary'], correct: 0 },
  { question: 'the city further south', options: ['Toronto', 'Calgary', 'Montreal'], correct: 0 },
  { question: 'not a member of the European Union', options: ['Switzerland', 'Latvia', 'Sweden'], correct: 0 },
  { question: 'a member of the European Union', options: ['Denmark', 'Switzerland', 'Dizniland'], correct: 0 },
  { question: 'the Nile does not flow through ___', options: ['Chad', 'Uganda', 'Sudan'], correct: 0 },
  { question: 'the Nile flows through ___', options: ['Uganda', 'Libya', 'Algeria'], correct: 0 },
  { question: 'the Appalachian Mountains are in ___', options: ['USA', 'Italy', 'Scotland'], correct: 0 },
  { question: 'the capital of Ireland', options: ['Dublin', 'Galway', 'Edinburgh'], correct: 0 },
  { question: 'knife of the Gurkhas', options: ['Kirku', 'Hancer', 'Blaid'], correct: 0 },
  { question: 'Singapore\'s population is less than ___', options: ['10 million', '1 million', '500'], correct: 0 },
  { question: 'Palace of Versailles is in ___', options: ['France', 'Austria', 'Vatican'], correct: 0 },
  { question: 'CN Tower is in ___', options: ['Toronto', 'Chicago', 'Seattle'], correct: 0 },
  { question: 'Harvard University is in ___', options: ['Cambridge', 'Oxford', 'Wadev'], correct: 0 },
  { question: 'Dartmouth College is in ___', options: ['Hanover', 'Norwich', 'Gog Reen'], correct: 0 },
  { question: 'University of Chicago is in ___', options: ['Chicago', 'Helsinki', 'Siberia'], correct: 0 },
  { question: 'UCLA is in ___', options: ['LA', 'UC', 'CL'], correct: 0 },
  { question: 'Dubrovnik is in ___', options: ['Croatia', 'Serbia', 'Ukraine'], correct: 0 },
  { question: 'Adriatic Sea cost runs along ___', options: ['Slovenia', 'Germany', 'Russia'], correct: 0 },
  { question: 'Indonesia\'s population is more than ___', options: ['859', '786 million', '364 million'], correct: 0 },
  { question: 'highest mountain in France', options: ['Mont Blanc', 'Mont Rouge', 'Mont Grand'], correct: 0 },
  { question: 'larger than Australia by area', options: ['Brazil', 'India', 'Germany'], correct: 0 },
  { question: 'a state in the USA', options: ['New Mexico', 'West Ohio', 'New Amsterdam'], correct: 0 },
  { question: 'a city in Kazakhstan', options: ['Almaty', 'Irat', 'Joshqun'], correct: 0 },
  { question: 'a city in France', options: ['Lyon', 'London', 'Cann'], correct: 0 },
  { question: 'a city in Germany', options: ['Dortmund', 'Borussia', 'Duisden'], correct: 0 },
  { question: 'a city in Greece', options: ['Patras', 'Hellas', 'Fellas'], correct: 0 },
  { question: 'a city in Morocco', options: ['Casablanca', 'Babol', 'Tabar'], correct: 0 },
  { question: 'a city in Canada', options: ['Edmonton', 'Burton', 'Sincity'], correct: 0 },
  { question: 'a city in England', options: ['Liverpool', 'Omaha', 'Newland'], correct: 0 },
  { question: 'a city in Sweden', options: ['Gothenburg', 'Malmsteen', 'Yngkorrkt'], correct: 0 },
  { question: 'a city in Finland', options: ['Turku', 'Takla', 'Tilki'], correct: 0 },
  { question: 'Caspian Sea doesn\'t border ___', options: ['China', 'Azerbaijan', 'Russia'], correct: 0 },
  { question: 'a neighbor of Armenia', options: ['Georgia', 'Carolina', 'Florida'], correct: 0 },
  { question: 'Sears Tower is in ___', options: ['Chicago', 'Toronto', 'Miami'], correct: 0 },
  { question: 'Arc de Triomphe is in ___', options: ['Paris', 'Lyon', 'Brussels'], correct: 0 },
  { question: 'Palazzo Vecchio is in ___', options: ['Florence', 'Rome', 'Milan'], correct: 0 },
  { question: 'Sydney Opera House is in ___', options: ['Sydney', 'Syndey', 'Sydeny'], correct: 0 },
  { question: 'a city in the northern hemisphere', options: ['Beijing', 'Sydney', 'Cape Town'], correct: 0 },
  { question: 'a city in the southern hemisphere', options: ['Buenos Aires', 'Dakar', 'Seoul'], correct: 0 },
  { question: 'not in the northern hemisphere', options: ['Paraguay', 'France', 'Egypt'], correct: 0 },
  { question: 'the larger city by population', options: ['Mexico City', 'Istanbul', 'Osaka'], correct: 0 },
  { question: 'the smaller city by population', options: ['Norway', 'Spain', 'Italy'], correct: 0 },
  { question: 'a country in the Northern Hemisphere', options: ['Egypt', 'South Africa', 'Uruguay'], correct: 0 },
  { question: 'a country in the Southern Hemisphere', options: ['Zambia', 'Tunisia', 'Morocco'], correct: 0 },
  { question: 'Mount Everest is located in ___', options: ['China', 'Russia', 'India'], correct: 0 },
  { question: 'not a city in Europe', options: ['Port Elizabeth', 'Tirana', 'Lyon'], correct: 0 },
  { question: 'not a city in Asia', options: ['Belgrade', 'Osaka', 'Baghdad'], correct: 0 },
  { question: 'a city in Northern America', options: ['Tijuana', 'Newshire', 'Pelwood'], correct: 0 },
  { question: 'a city in Europe', options: ['Paris', 'France', 'Argentina'], correct: 0 },
  { question: 'the largest continent', options: ['Asia', 'America', 'Africa'], correct: 0 },
  { question: 'larger country by population', options: ['Brazil', 'Russia', 'Japan'], correct: 0 },
  { question: 'he cut Van Gogh\'s ear', options: ['Van Gogh', 'E. Scissorhands', 'P. Gaugin'], correct: 0 },
  { question: '"cogito ergo sum"', options: ['Descartes', 'Leibniz', 'Shakespeare'], correct: 0 },
  { question: 'painted the Sistine Chapel', options: ['Michelangelo', 'Donatello', 'Splinter'], correct: 0 },
  { question: 'Wolfgang ___ Mozart', options: ['amadeus', 'theo', 'constanze'], correct: 0 },
  { question: 'painted Mona Lisa', options: ['Leonardo da Vinci', 'Michelangelo', 'Rene Magritte'], correct: 0 },
  { question: 'painted The Last Supper', options: ['Leonardo da Vinci', 'Pablo Picasso', 'Claude Monet'], correct: 0 },
  { question: 'painted Girl with a Pearl Earring', options: ['Johannes Vermeer', 'Rene Magritte', 'Edouard Manet'], correct: 0 },
  { question: 'painted American Gothic', options: ['Grant Wood', 'Jackson Pollock', 'Homer Simpson'], correct: 0 },
  { question: 'painted The Scream', options: ['Edvard Munch', 'Wes Craven', 'Jackson Pollock'], correct: 0 },
  { question: 'former Chicago Bulls player', options: ['Jerry Sloan', 'Karl Malone', 'John Stockton'], correct: 0 },
  { question: 'founder of Louis Vuitton', options: ['Louis Vuitton', 'Coco de Gabbana', 'Pepe LePeu'], correct: 0 },
  { question: 'French haute couture fashion designer', options: ['Jean Paul Gaultier', 'Anna Wintour', 'Domenico Dolce'], correct: 0 },
  { question: 'chess legend with no defeats against AI', options: ['Bobby Fischer', 'Garry Kasparov', 'Joseph Saddler'], correct: 0 },
  { question: 'former British Prime Minister', options: ['Margaret Thatcher', 'Tony Blare', 'Gordon Cameron'], correct: 0 },
  { question: 'American actress with no Oscars', options: ['Marilyn Monroe', 'Helen Mirren', 'Meryl Streep'], correct: 0 },
  { question: 'Renaissance astronomer', options: ['Copernicus', 'Isaac Newton', 'Leonardo DiCaprio'], correct: 0 },
  { question: 'South Korean football player', options: ['Park Ji-sung', 'Park Sun Jae', 'Ji-Soo Kwon'], correct: 0 },
  { question: 'American skater', options: ['Rodney Mullen', 'Tony Eagle', 'John Eagleflag'], correct: 0 },
  { question: 'Muhammad Ali\'s first defeat was vs. ___', options: ['Joe Fraizer', 'George Foreman', 'Floyd Patterson'], correct: 0 },
  { question: 'founded Ford Motor Company', options: ['Henry Ford', 'Henry Fonda', 'Tom Ford'], correct: 0 },
  { question: '13th century philosopher', options: ['Roger Bacon', 'Francis Bacon', 'Kevin Bacon'], correct: 0 },
  { question: 'not a Nobel Prize winner', options: ['M. Gandhi', 'B. Obama', 'H. Kissinger'], correct: 0 },
  { question: 'French fashion designer', options: ['Coco Chanel', 'Donna Karan', 'Shia LeBeouf'], correct: 0 },
  { question: 'English chemist and physicist', options: ['M. Faraday', 'N. Tesla', 'A. Einstein'], correct: 0 },
  { question: 'leading figure in pop art movement', options: ['Andy Warhol', 'Michael Ciccone', 'Jackson Pollock'], correct: 0 },
  { question: 'English football player', options: ['Wayne Rooney', 'George Michael', 'Julian Casablancas'], correct: 0 },
  { question: 'American football player', options: ['Tom Brady', 'Wayne Brady', 'Bradley Manning'], correct: 0 },
  { question: 'Germanl football player', options: ['Philipp Lahm', 'Marc Janko', 'Heinrich Hertz'], correct: 0 },
  { question: 'Italian football player', options: ['Mario Balotelli', 'Vito Corleone', 'Enrico Fermi'], correct: 0 },
  { question: 'Bulgarian football player', options: ['Dimitar Berbatov', 'Hristo Sirakov', 'Ayan Stoichkov'], correct: 0 },
  { question: 'Japanese football player', options: ['Shinji Okazaki', 'Park Ji-Sun', 'Ichiro Suzuki'], correct: 0 },
  { question: 'American basketball player', options: ['Scottie Pippen', 'Landon Donovan', 'Steve Nash'], correct: 0 },
  { question: 'co-founder of Microsoft', options: ['Paul Allen', 'Steve Gates', 'Steve Ballmer'], correct: 0 },
  { question: 'unveiled the iMac in 1998', options: ['Steve Jobs', 'Bill Gates', 'Justin Bieber'], correct: 0 },
  { question: 'Braille was invented by ___', options: ['Louis Braille', 'Louis CK', 'Helen Keller'], correct: 0 },
  { question: 'Australian Formula 1 driver', options: ['Mark Webber', 'Sebastian Vettel', 'Lewis Hamilton'], correct: 0 },
  { question: 'designer of the Sydney Opera House', options: ['Joern Utzon', 'Malcolm Young', 'Steve Irwin'], correct: 0 },
  { question: 'French goalkeeper', options: ['Fabien Barthez', 'Frank Ribery', 'G. Ardien deBut'], correct: 0 },
  { question: 'former Manchester United player', options: ['Eric Cantona', 'David Seaman', 'Alan Shearer'], correct: 0 },
  { question: 'scored in the 1998 FIFA World Cup', options: ['Zinedine Zidane', 'George Weah', 'Johann Cruyff'], correct: 0 },
  { question: 'American standup', options: ['Richard Pryor', 'Eddie Izzard', 'Ricky Gervais'], correct: 0 },
  { question: 'former Mr. Olympia', options: ['A. Schwarzenegger', 'Flex Wheeler', 'Kevin Levrone'], correct: 0 },
  { question: '40th president of the USA', options: ['Ronald Reagan', 'T. Roosevelt', 'Gerald Ford'], correct: 0 },
  { question: 'American gangster', options: ['Al Capone', 'Al Pacino', 'Al Jazeera'], correct: 0 },
  { question: 'French general and statesman', options: ['Charles de Gaulle', 'Jacques Cousteau', 'Thierry Henry'], correct: 0 },
  { question: '"Vini, vidi, vici"', options: ['Julius Caesar', 'Genghis Khan', 'Tony Montana'], correct: 0 },
  { question: 'a student of Socrates', options: ['Pluto', 'Dionysus', 'Apollo'], correct: 0 },
  { question: 'a student of Plato', options: ['Aristotle', 'Socrates', 'Tzatziki'], correct: 0 },
  { question: 'famous magician', options: ['Houdini', 'Panentellur', 'Karl Popper'], correct: 0 },
  { question: '"Green Eggs & Ham" is penned by this man', options: ['Dr. Seuss', 'Dr. Juice', 'Dr. Snooze'], correct: 0 },
  { question: 'fictional detective', options: ['Sherlock Holmes', 'Lawrence Walgrave', 'Lex Luthor'], correct: 0 },
  { question: 'a character by Agatha Christie', options: ['Hercule Poirot', 'Harry Potter', 'Perry Mason'], correct: 0 },
  { question: 'she wrote Harry Potter', options: ['J. K. Rowling', 'S. Meyer', 'A. Christie'], correct: 0 },
  { question: 'he wrote The BFG', options: ['Roald Dahl', 'Maurice Sendak', 'Shel Sliverstein'], correct: 0 },
  { question: 'The Hobbit was written by a ___', options: ['human', 'dwarf', 'hobbit'], correct: 0 },
  { question: 'a hobbit in The Hobbit', options: ['Bilbo', 'Malmo', 'Elmo'], correct: 0 },
  { question: 'he was not a doctor but a writer', options: ['Dr. Seuss', 'Dr. Whose', 'Dr. Choose'], correct: 0 },
  { question: 'he wrote Alice in Wonderland', options: ['Lewis Carroll', 'Roald Dahl', 'John Ruskin'], correct: 0 },
  { question: 'he wrote War and Peace', options: ['Leo Tolstoy', 'F. Dostoyevsky', 'Nikolai Gogol'], correct: 0 },
  { question: 'Irish novelist', options: ['James Joyce', 'James Hetfield', 'James Cameron'], correct: 0 }
];

export function getRank(score: number): string {
  if (score === 0) return 'Really?';
  if (score <= 200) return 'Heartbreaking';
  if (score <= 300) return 'F for Effort';
  if (score <= 400) return 'Sad';
  if (score <= 500) return 'Unfortunate';
  if (score <= 700) return 'Poor';
  if (score <= 900) return 'Amateur';
  if (score <= 1200) return 'Tolerable';
  if (score <= 1500) return 'Average';
  if (score <= 1800) return 'Acceptable';
  if (score <= 2100) return 'Decent';
  if (score <= 2400) return 'Respectable';
  if (score <= 2800) return 'Good';
  if (score <= 3200) return 'Smart';
  if (score <= 3600) return 'Great';
  if (score <= 4000) return 'Terrific';
  if (score <= 4500) return 'Fantastic';
  if (score <= 5000) return 'Excellent';
  if (score <= 5500) return 'Elite';
  if (score <= 6200) return 'Genius';
  if (score <= 7000) return 'Mastermind';
  return 'Super Smart\!';
}

function shuffleOptions(q: Question): Question {
  const correctText = q.options[q.correct];
  const opts = [...q.options] as [string, string, string];
  for (let i = opts.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [opts[i], opts[j]] = [opts[j], opts[i]];
  }
  return { ...q, options: opts, correct: opts.indexOf(correctText) };
}

export function shuffleQuestions(questions: Question[]): Question[] {
  const shuffled = [...questions];
  for (let i = shuffled.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
  }
  return shuffled.map(shuffleOptions);
}
